version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Africa/Nairobi
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "security(frontend)"

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Africa/Nairobi
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "security(backend)"
