import bcrypt from 'bcryptjs'
import crypto from 'node:crypto'
import cors from 'cors'
import express from 'express'
import helmet from 'helmet'
import {z} from 'zod'
import {config} from './config.js'
import {authenticate,authorize,createToken,roles} from './auth.js'
import {audit} from './audit.js'
import {query,transaction} from './db.js'

const app=express()
app.disable('x-powered-by')
app.use(helmet())
app.use(cors({origin:config.frontendOrigin}))
app.use(express.json({limit:'1mb'}))

const validate=schema=>(req,res,next)=>{const result=schema.safeParse(req.body);if(!result.success)return res.status(400).json({error:'Please correct the submitted information.',details:result.error.flatten()});req.validated=result.data;next()}
const loginSchema=z.object({email:z.string().email().max(255),password:z.string().min(8).max(128)})
const passwordSchema=z.string().min(10).max(128).regex(/[A-Z]/,'Include an uppercase letter.').regex(/[a-z]/,'Include a lowercase letter.').regex(/[0-9]/,'Include a number.')
const assignmentSchema=z.object({title:z.string().min(4).max(240),description:z.string().max(5000).default(''),division:z.string().min(2).max(160),dueDate:z.string().nullable().optional(),priority:z.enum(['Low','Normal','High','Critical']).default('Normal'),memberIds:z.array(z.string().uuid()).default([])})

app.get('/api/health',async(_req,res,next)=>{try{await query('SELECT 1');res.json({status:'healthy',service:'psc-app2-api',database:'connected'})}catch(error){next(error)}})
app.post('/api/auth/login',validate(loginSchema),async(req,res,next)=>{try{const result=await query('SELECT id,name,email,password_hash,role,division,status,active,token_version FROM users WHERE lower(email)=lower($1)',[req.validated.email]);const user=result.rows[0];if(!user||!user.active||!await bcrypt.compare(req.validated.password,user.password_hash))return res.status(401).json({error:'Login unsuccessful. Verify your official PSC email and password. If the problem continues, recover your password or ask an administrator to confirm that your account is active.'});delete user.password_hash;res.json({token:createToken(user),user})}catch(error){next(error)}})
app.get('/api/auth/me',authenticate,(req,res)=>res.json(req.user))
app.post('/api/auth/logout',authenticate,async(req,res,next)=>{try{await query('UPDATE users SET token_version=token_version+1,updated_at=NOW() WHERE id=$1',[req.user.id]);res.status(204).end()}catch(error){next(error)}})
app.post('/api/auth/change-password',authenticate,validate(z.object({currentPassword:z.string().min(8).max(128),newPassword:passwordSchema})),async(req,res,next)=>{try{const current=(await query('SELECT password_hash FROM users WHERE id=$1',[req.user.id])).rows[0];if(!current||!await bcrypt.compare(req.validated.currentPassword,current.password_hash))return res.status(400).json({error:'The current password is incorrect.'});if(await bcrypt.compare(req.validated.newPassword,current.password_hash))return res.status(400).json({error:'Choose a password different from the current password.'});const hash=await bcrypt.hash(req.validated.newPassword,12);const updated=(await query('UPDATE users SET password_hash=$1,token_version=token_version+1,updated_at=NOW() WHERE id=$2 RETURNING id,name,email,role,division,status,token_version',[hash,req.user.id])).rows[0];res.json({token:createToken(updated),user:updated})}catch(error){next(error)}})
app.post('/api/auth/forgot-password',validate(z.object({email:z.string().email().max(255)})),async(req,res,next)=>{try{const user=(await query('SELECT id FROM users WHERE lower(email)=lower($1) AND active=TRUE',[req.validated.email])).rows[0];let resetToken;if(user){resetToken=crypto.randomBytes(32).toString('hex');const tokenHash=crypto.createHash('sha256').update(resetToken).digest('hex');await transaction(async client=>{await client.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=$1 AND used_at IS NULL',[user.id]);await client.query("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')",[user.id,tokenHash])})}const response={message:'If the account exists, password reset instructions have been prepared.'};if(config.environment!=='production'&&resetToken)response.resetToken=resetToken;res.json(response)}catch(error){next(error)}})
app.post('/api/auth/reset-password',validate(z.object({token:z.string().length(64),newPassword:passwordSchema})),async(req,res,next)=>{try{const tokenHash=crypto.createHash('sha256').update(req.validated.token).digest('hex');const result=await transaction(async client=>{const reset=(await client.query('SELECT id,user_id FROM password_reset_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW() FOR UPDATE',[tokenHash])).rows[0];if(!reset)return null;const hash=await bcrypt.hash(req.validated.newPassword,12);await client.query('UPDATE users SET password_hash=$1,token_version=token_version+1,updated_at=NOW() WHERE id=$2',[hash,reset.user_id]);await client.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE id=$1',[reset.id]);return true});if(!result)return res.status(400).json({error:'This password reset link is invalid or has expired.'});res.json({message:'Password updated. You can now sign in.'})}catch(error){next(error)}})

app.get('/api/users',authenticate,authorize('Administrator','Research Manager'),async(_req,res,next)=>{try{const result=await query(`SELECT u.id,u.name,u.email,u.role,u.division,u.status,u.active,COUNT(am.assignment_id) FILTER(WHERE a.status!='Completed')::int active_assignments,COUNT(am.assignment_id) FILTER(WHERE a.status='Completed')::int completed_assignments FROM users u LEFT JOIN assignment_members am ON am.user_id=u.id LEFT JOIN assignments a ON a.id=am.assignment_id GROUP BY u.id ORDER BY u.name`);res.json(result.rows)}catch(error){next(error)}})
app.patch('/api/users/:id/role',authenticate,authorize('Administrator'),validate(z.object({role:z.enum(roles)})),async(req,res,next)=>{try{const updated=await transaction(async client=>{const result=await client.query('UPDATE users SET role=$1,updated_at=NOW() WHERE id=$2 RETURNING id,name,email,role,division,status',[req.validated.role,req.params.id]);if(!result.rows[0])return null;await audit(client,req.user.id,'ROLE_CHANGED','user',req.params.id,req.validated);return result.rows[0]});if(!updated)return res.status(404).json({error:'Member not found.'});res.json(updated)}catch(error){next(error)}})

app.get('/api/assignments',authenticate,async(req,res,next)=>{try{const all=['Administrator','Research Manager'].includes(req.user.role);const result=await query(`SELECT a.*,creator.name created_by_name,COALESCE(json_agg(json_build_object('id',u.id,'name',u.name,'role',am.member_role)) FILTER(WHERE u.id IS NOT NULL),'[]') members FROM assignments a JOIN users creator ON creator.id=a.created_by LEFT JOIN assignment_members am ON am.assignment_id=a.id LEFT JOIN users u ON u.id=am.user_id WHERE $1::boolean OR EXISTS(SELECT 1 FROM assignment_members mine WHERE mine.assignment_id=a.id AND mine.user_id=$2) GROUP BY a.id,creator.name ORDER BY a.created_at DESC`,[all,req.user.id]);res.json(result.rows)}catch(error){next(error)}})
app.post('/api/assignments',authenticate,authorize('Administrator','Research Manager'),validate(assignmentSchema),async(req,res,next)=>{try{const created=await transaction(async client=>{const {title,description,division,dueDate,priority,memberIds}=req.validated;const result=await client.query('INSERT INTO assignments(title,description,division,due_date,priority,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[title,description,division,dueDate||null,priority,req.user.id]);for(const id of memberIds)await client.query('INSERT INTO assignment_members(assignment_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[result.rows[0].id,id]);await audit(client,req.user.id,'ASSIGNMENT_CREATED','assignment',result.rows[0].id,{title,memberIds});return result.rows[0]});res.status(201).json(created)}catch(error){next(error)}})
app.patch('/api/assignments/:id/status',authenticate,validate(z.object({status:z.enum(['Not Started','In Progress','Ready for Review','Completed','Overdue'])})),async(req,res,next)=>{try{const membership=await query('SELECT 1 FROM assignment_members WHERE assignment_id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!['Administrator','Research Manager'].includes(req.user.role)&&!membership.rowCount)return res.status(403).json({error:'You are not assigned to this work.'});const result=await query('UPDATE assignments SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.validated.status,req.params.id]);if(!result.rows[0])return res.status(404).json({error:'Assignment not found.'});res.json(result.rows[0])}catch(error){next(error)}})
app.post('/api/assignments/:id/members',authenticate,authorize('Administrator','Research Manager'),validate(z.object({userId:z.string().uuid(),memberRole:z.enum(['Lead','Contributor','Reviewer']).default('Contributor')})),async(req,res,next)=>{try{await query('INSERT INTO assignment_members(assignment_id,user_id,member_role) VALUES($1,$2,$3) ON CONFLICT(assignment_id,user_id) DO UPDATE SET member_role=EXCLUDED.member_role',[req.params.id,req.validated.userId,req.validated.memberRole]);res.status(204).end()}catch(error){next(error)}})
app.get('/api/assignments/:id/comments',authenticate,async(req,res,next)=>{try{const result=await query('SELECT c.id,c.body,c.created_at,u.id author_id,u.name author_name FROM assignment_comments c JOIN users u ON u.id=c.author_id WHERE c.assignment_id=$1 ORDER BY c.created_at',[req.params.id]);res.json(result.rows)}catch(error){next(error)}})
app.post('/api/assignments/:id/comments',authenticate,validate(z.object({body:z.string().min(1).max(4000)})),async(req,res,next)=>{try{const result=await query('INSERT INTO assignment_comments(assignment_id,author_id,body) VALUES($1,$2,$3) RETURNING *',[req.params.id,req.user.id,req.validated.body]);res.status(201).json(result.rows[0])}catch(error){next(error)}})

app.get('/api/alerts',authenticate,async(req,res,next)=>{try{const result=await query(`SELECT a.*,u.name created_by_name FROM alerts a JOIN users u ON u.id=a.created_by WHERE(a.audience_role IS NULL OR a.audience_role=$1)AND(a.expires_at IS NULL OR a.expires_at>NOW()) ORDER BY a.created_at DESC`,[req.user.role]);res.json(result.rows)}catch(error){next(error)}})
app.post('/api/alerts',authenticate,authorize('Administrator','Research Manager'),validate(z.object({title:z.string().min(3).max(200),body:z.string().min(3).max(4000),severity:z.enum(['Information','Important','Urgent']).default('Information'),audienceRole:z.enum(roles).nullable().default(null)})),async(req,res,next)=>{try{const {title,body,severity,audienceRole}=req.validated;const result=await query('INSERT INTO alerts(title,body,severity,audience_role,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[title,body,severity,audienceRole,req.user.id]);res.status(201).json(result.rows[0])}catch(error){next(error)}})
app.get('/api/analytics/overview',authenticate,authorize('Administrator','Research Manager'),async(_req,res,next)=>{try{const [statuses,workloads,members]=await Promise.all([query('SELECT status,COUNT(*)::int total FROM assignments GROUP BY status'),query(`SELECT u.id,u.name,COUNT(am.assignment_id) FILTER(WHERE a.status!='Completed')::int active FROM users u LEFT JOIN assignment_members am ON am.user_id=u.id LEFT JOIN assignments a ON a.id=am.assignment_id GROUP BY u.id ORDER BY active DESC`),query('SELECT role,COUNT(*)::int total FROM users WHERE active=TRUE GROUP BY role')]);res.json({assignmentStatuses:statuses.rows,workloads:workloads.rows,membersByRole:members.rows})}catch(error){next(error)}})
app.get('/api/audit-logs',authenticate,authorize('Administrator'),async(_req,res,next)=>{try{res.json((await query('SELECT l.*,u.name user_name FROM audit_logs l LEFT JOIN users u ON u.id=l.user_id ORDER BY l.created_at DESC LIMIT 250')).rows)}catch(error){next(error)}})

app.use((_req,res)=>res.status(404).json({error:'API endpoint not found.'}))
app.use((error,_req,res,_next)=>{console.error(error);res.status(500).json({error:config.environment==='production'?'The service could not complete your request.':error.message})})
export default app
