import bcrypt from 'bcryptjs'
import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import cors from 'cors'
import express from 'express'
import helmet from 'helmet'
import {z} from 'zod'
import {config} from './config.js'
import {authenticate,authorize,createToken,roles} from './auth.js'
import {audit} from './audit.js'
import {query,transaction} from './db.js'
import {mailStatus,sendMail} from './mailer.js'

const app=express()
app.disable('x-powered-by')
app.use(helmet())
app.use(cors({origin:config.frontendOrigin}))
app.use('/api/assignments/:id/attachments',express.raw({type:'application/octet-stream',limit:`${config.maxUploadMb}mb`}))
app.use('/api/knowledge',express.raw({type:'application/octet-stream',limit:`${config.maxUploadMb}mb`}))
app.use('/api/knowledge/:id/versions',express.raw({type:'application/octet-stream',limit:`${config.maxUploadMb}mb`}))
app.use(express.json({limit:'1mb'}))

const validate=schema=>(req,res,next)=>{const result=schema.safeParse(req.body);if(!result.success)return res.status(400).json({error:'Please correct the submitted information.',details:result.error.flatten()});req.validated=result.data;next()}
const loginSchema=z.object({email:z.string().email().max(255),password:z.string().min(8).max(128)})
const passwordSchema=z.string().min(10).max(128).regex(/[A-Z]/,'Include an uppercase letter.').regex(/[a-z]/,'Include a lowercase letter.').regex(/[0-9]/,'Include a number.')
const testEmailSchema=z.object({email:z.string().email().max(255)})
const assignmentSchema=z.object({title:z.string().min(4).max(240),description:z.string().max(5000).default(''),division:z.string().min(2).max(160),dueDate:z.string().nullable().optional(),priority:z.enum(['Low','Normal','High','Critical']).default('Normal'),memberIds:z.array(z.string().uuid()).default([])})
const knowledgeSchema=z.object({title:z.string().min(3).max(240),description:z.string().max(5000).default(''),category:z.string().min(2).max(100),tags:z.array(z.string().min(1).max(60)).max(30).default([]),author:z.string().max(200).nullable().optional(),documentDate:z.string().nullable().optional()})
const canAccessAssignment=async(user,id)=>['Administrator','Research Manager'].includes(user.role)||(await query('SELECT 1 FROM assignment_members WHERE assignment_id=$1 AND user_id=$2',[id,user.id])).rowCount>0
const knowledgeManagers=['Administrator','Research Manager']
const canManageKnowledge=user=>knowledgeManagers.includes(user.role)
const canReviewKnowledge=user=>[...knowledgeManagers,'Reviewer'].includes(user.role)
const canReadKnowledge=async(user,id)=>canReviewKnowledge(user)||(await query("SELECT 1 FROM knowledge_items WHERE id=$1 AND(status='Published' OR created_by=$2)",[id,user.id])).rowCount>0

app.get('/api/health',async(_req,res,next)=>{try{await query('SELECT 1');res.json({status:'healthy',service:'psc-app2-api',database:'connected'})}catch(error){next(error)}})
app.post('/api/auth/login',validate(loginSchema),async(req,res,next)=>{try{const result=await query('SELECT id,name,email,password_hash,role,division,status,active,token_version,must_change_password FROM users WHERE lower(email)=lower($1)',[req.validated.email]);const user=result.rows[0];if(!user||!user.active||!await bcrypt.compare(req.validated.password,user.password_hash)){await query("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details)VALUES($1,'LOGIN_FAILED','session',$2,$3)",[user?.id||null,user?.id||null,JSON.stringify({email:req.validated.email})]);return res.status(401).json({error:'Login unsuccessful. Verify your official PSC email and password. If the problem continues, recover your password or ask an administrator to confirm that your account is active.'})}delete user.password_hash;await query("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details)VALUES($1::uuid,'LOGIN_SUCCEEDED','session',$1::uuid::text,$2)",[user.id,JSON.stringify({email:user.email,role:user.role})]);res.json({token:createToken(user),user})}catch(error){next(error)}})
app.get('/api/auth/me',authenticate,(req,res)=>res.json(req.user))
app.post('/api/auth/logout',authenticate,async(req,res,next)=>{try{await transaction(async client=>{await client.query('UPDATE users SET token_version=token_version+1,updated_at=NOW() WHERE id=$1',[req.user.id]);await audit(client,req.user.id,'LOGOUT','session',req.user.id,{})});res.status(204).end()}catch(error){next(error)}})
app.post('/api/auth/change-password',authenticate,validate(z.object({currentPassword:z.string().min(8).max(128),newPassword:passwordSchema})),async(req,res,next)=>{try{const current=(await query('SELECT password_hash FROM users WHERE id=$1',[req.user.id])).rows[0];if(!current||!await bcrypt.compare(req.validated.currentPassword,current.password_hash))return res.status(400).json({error:'The current password is incorrect.'});if(await bcrypt.compare(req.validated.newPassword,current.password_hash))return res.status(400).json({error:'Choose a password different from the current password.'});const hash=await bcrypt.hash(req.validated.newPassword,12);const updated=(await query('UPDATE users SET password_hash=$1,must_change_password=FALSE,token_version=token_version+1,updated_at=NOW() WHERE id=$2 RETURNING id,name,email,role,division,status,token_version,must_change_password',[hash,req.user.id])).rows[0];res.json({token:createToken(updated),user:updated})}catch(error){next(error)}})
app.post('/api/auth/forgot-password',validate(z.object({email:z.string().email().max(255)})),async(req,res,next)=>{try{const user=(await query('SELECT id FROM users WHERE lower(email)=lower($1) AND active=TRUE',[req.validated.email])).rows[0];let resetToken;if(user){resetToken=crypto.randomBytes(32).toString('hex');const tokenHash=crypto.createHash('sha256').update(resetToken).digest('hex');await transaction(async client=>{await client.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=$1 AND used_at IS NULL',[user.id]);await client.query("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')",[user.id,tokenHash])})}const response={message:'If the account exists, password reset instructions have been prepared.'};if(config.environment!=='production'&&resetToken)response.resetToken=resetToken;res.json(response)}catch(error){next(error)}})
app.post('/api/auth/reset-password',validate(z.object({token:z.string().length(64),newPassword:passwordSchema})),async(req,res,next)=>{try{const tokenHash=crypto.createHash('sha256').update(req.validated.token).digest('hex');const result=await transaction(async client=>{const reset=(await client.query('SELECT id,user_id FROM password_reset_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW() FOR UPDATE',[tokenHash])).rows[0];if(!reset)return null;const hash=await bcrypt.hash(req.validated.newPassword,12);await client.query('UPDATE users SET password_hash=$1,token_version=token_version+1,updated_at=NOW() WHERE id=$2',[hash,reset.user_id]);await client.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE id=$1',[reset.id]);return true});if(!result)return res.status(400).json({error:'This password reset link is invalid or has expired.'});res.json({message:'Password updated. You can now sign in.'})}catch(error){next(error)}})

app.get('/api/users',authenticate,authorize('Administrator','Research Manager'),async(_req,res,next)=>{try{const result=await query(`SELECT u.id,u.name,u.email,u.role,u.division,u.status,u.active,COUNT(am.assignment_id) FILTER(WHERE a.status!='Completed')::int active_assignments,COUNT(am.assignment_id) FILTER(WHERE a.status='Completed')::int completed_assignments FROM users u LEFT JOIN assignment_members am ON am.user_id=u.id LEFT JOIN assignments a ON a.id=am.assignment_id GROUP BY u.id ORDER BY u.name`);res.json(result.rows)}catch(error){next(error)}})
app.post('/api/users',authenticate,authorize('Administrator'),validate(z.object({name:z.string().min(3).max(160),email:z.string().email().max(255),role:z.enum(roles),division:z.string().min(2).max(160),temporaryPassword:passwordSchema.optional()})),async(req,res,next)=>{try{const temporaryPassword=req.validated.temporaryPassword||`Psc!${crypto.randomBytes(6).toString('base64url')}9`;const passwordHash=await bcrypt.hash(temporaryPassword,12);const created=await transaction(async client=>{const row=(await client.query('INSERT INTO users(name,email,password_hash,role,division,must_change_password) VALUES($1,lower($2),$3,$4,$5,TRUE) RETURNING id,name,email,role,division,status,active,must_change_password',[req.validated.name.trim(),req.validated.email.trim(),passwordHash,req.validated.role,req.validated.division.trim()])).rows[0];await audit(client,req.user.id,'USER_CREATED','user',row.id,{email:row.email,role:row.role,division:row.division});return row});res.status(201).json({...created,temporary_password:temporaryPassword})}catch(error){if(error.code==='23505')return res.status(409).json({error:'An account already exists for this email address.'});next(error)}})
app.patch('/api/users/:id',authenticate,authorize('Administrator'),validate(z.object({name:z.string().min(3).max(160),email:z.string().email().max(255),role:z.enum(roles),division:z.string().min(2).max(160),status:z.enum(['Available','Busy','Away']),active:z.boolean()})),async(req,res,next)=>{try{const updated=await transaction(async client=>{const current=(await client.query('SELECT role,active FROM users WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!current)return {kind:'missing'};const removesAdministrator=current.role==='Administrator'&&(req.validated.role!=='Administrator'||!req.validated.active);if(removesAdministrator){const count=Number((await client.query("SELECT COUNT(*) total FROM users WHERE role='Administrator' AND active=TRUE")).rows[0].total);if(count<=1)return {kind:'last-admin'}}const row=(await client.query('UPDATE users SET name=$1,email=lower($2),role=$3,division=$4,status=$5,active=$6,token_version=CASE WHEN active<>$6 THEN token_version+1 ELSE token_version END,updated_at=NOW() WHERE id=$7 RETURNING id,name,email,role,division,status,active,must_change_password',[req.validated.name.trim(),req.validated.email.trim(),req.validated.role,req.validated.division.trim(),req.validated.status,req.validated.active,req.params.id])).rows[0];await audit(client,req.user.id,'USER_UPDATED','user',row.id,{role:row.role,division:row.division,status:row.status,active:row.active});return {kind:'updated',row}});if(updated.kind==='missing')return res.status(404).json({error:'Member not found.'});if(updated.kind==='last-admin')return res.status(409).json({error:'The final active administrator cannot be demoted or deactivated.'});res.json(updated.row)}catch(error){if(error.code==='23505')return res.status(409).json({error:'That email address is already in use.'});next(error)}})
app.patch('/api/users/:id/role',authenticate,authorize('Administrator'),validate(z.object({role:z.enum(roles)})),async(req,res,next)=>{try{const updated=await transaction(async client=>{const current=(await client.query('SELECT role FROM users WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!current)return {kind:'missing'};if(current.role==='Administrator'&&req.validated.role!=='Administrator'){const count=Number((await client.query("SELECT COUNT(*) total FROM users WHERE role='Administrator' AND active=TRUE")).rows[0].total);if(count<=1)return {kind:'last-admin'}}const row=(await client.query('UPDATE users SET role=$1,updated_at=NOW() WHERE id=$2 RETURNING id,name,email,role,division,status,active',[req.validated.role,req.params.id])).rows[0];await audit(client,req.user.id,'ROLE_CHANGED','user',req.params.id,req.validated);return {kind:'updated',row}});if(updated.kind==='missing')return res.status(404).json({error:'Member not found.'});if(updated.kind==='last-admin')return res.status(409).json({error:'The final active administrator cannot be demoted.'});res.json(updated.row)}catch(error){next(error)}})
app.post('/api/users/:id/reset-password',authenticate,authorize('Administrator'),async(req,res,next)=>{try{const temporaryPassword=`Psc!${crypto.randomBytes(6).toString('base64url')}9`;const hash=await bcrypt.hash(temporaryPassword,12);const updated=await transaction(async client=>{const row=(await client.query('UPDATE users SET password_hash=$1,must_change_password=TRUE,token_version=token_version+1,updated_at=NOW() WHERE id=$2 RETURNING id,name,email',[hash,req.params.id])).rows[0];if(row)await audit(client,req.user.id,'USER_PASSWORD_RESET','user',row.id,{email:row.email});return row});if(!updated)return res.status(404).json({error:'Member not found.'});res.json({message:'Temporary password created. Existing sessions were ended.',temporaryPassword})}catch(error){next(error)}})

app.get('/api/assignments',authenticate,async(req,res,next)=>{try{const all=['Administrator','Research Manager'].includes(req.user.role);const result=await query(`SELECT a.*,creator.name created_by_name,COALESCE(json_agg(json_build_object('id',u.id,'name',u.name,'role',am.member_role)) FILTER(WHERE u.id IS NOT NULL),'[]') members FROM assignments a JOIN users creator ON creator.id=a.created_by LEFT JOIN assignment_members am ON am.assignment_id=a.id LEFT JOIN users u ON u.id=am.user_id WHERE $1::boolean OR EXISTS(SELECT 1 FROM assignment_members mine WHERE mine.assignment_id=a.id AND mine.user_id=$2) GROUP BY a.id,creator.name ORDER BY a.created_at DESC`,[all,req.user.id]);res.json(result.rows)}catch(error){next(error)}})
app.post('/api/assignments',authenticate,authorize('Administrator','Research Manager'),validate(assignmentSchema),async(req,res,next)=>{try{const created=await transaction(async client=>{const {title,description,division,dueDate,priority,memberIds}=req.validated;const result=await client.query('INSERT INTO assignments(title,description,division,due_date,priority,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[title,description,division,dueDate||null,priority,req.user.id]);for(const id of memberIds)await client.query('INSERT INTO assignment_members(assignment_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[result.rows[0].id,id]);await client.query('INSERT INTO assignment_history(assignment_id,user_id,action,details) VALUES($1,$2,$3,$4)',[result.rows[0].id,req.user.id,'CREATED',JSON.stringify({title,memberIds})]);await audit(client,req.user.id,'ASSIGNMENT_CREATED','assignment',result.rows[0].id,{title,memberIds});return result.rows[0]});res.status(201).json(created)}catch(error){next(error)}})
app.patch('/api/assignments/:id',authenticate,authorize('Administrator','Research Manager'),validate(assignmentSchema.omit({memberIds:true})),async(req,res,next)=>{try{const {title,description,division,dueDate,priority}=req.validated;const result=await transaction(async client=>{const updated=(await client.query('UPDATE assignments SET title=$1,description=$2,division=$3,due_date=$4,priority=$5,updated_at=NOW() WHERE id=$6 RETURNING *',[title,description,division,dueDate||null,priority,req.params.id])).rows[0];if(updated)await client.query('INSERT INTO assignment_history(assignment_id,user_id,action,details) VALUES($1,$2,$3,$4)',[req.params.id,req.user.id,'UPDATED',JSON.stringify({title,division,dueDate,priority})]);return updated});if(!result)return res.status(404).json({error:'Assignment not found.'});res.json(result)}catch(error){next(error)}})
app.delete('/api/assignments/:id',authenticate,authorize('Administrator','Research Manager'),async(req,res,next)=>{try{const files=(await query('SELECT stored_name FROM assignment_attachments WHERE assignment_id=$1',[req.params.id])).rows;const result=await query('DELETE FROM assignments WHERE id=$1 RETURNING id',[req.params.id]);if(!result.rowCount)return res.status(404).json({error:'Assignment not found.'});await Promise.all(files.map(file=>fs.unlink(path.resolve(config.uploadDir,file.stored_name)).catch(()=>{})));res.status(204).end()}catch(error){next(error)}})
app.patch('/api/assignments/:id/status',authenticate,validate(z.object({status:z.enum(['Not Started','In Progress','Ready for Review','Completed','Overdue'])})),async(req,res,next)=>{try{if(!await canAccessAssignment(req.user,req.params.id))return res.status(403).json({error:'You are not assigned to this work.'});if(req.validated.status==='Completed'&&!['Administrator','Research Manager','Reviewer'].includes(req.user.role))return res.status(403).json({error:'Only a reviewer or manager can approve completed work.'});const result=await transaction(async client=>{const updated=(await client.query('UPDATE assignments SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.validated.status,req.params.id])).rows[0];if(updated)await client.query('INSERT INTO assignment_history(assignment_id,user_id,action,details) VALUES($1,$2,$3,$4)',[req.params.id,req.user.id,req.validated.status==='Completed'?'APPROVED':'STATUS_CHANGED',JSON.stringify({status:req.validated.status})]);return updated});if(!result)return res.status(404).json({error:'Assignment not found.'});res.json(result)}catch(error){next(error)}})
app.post('/api/assignments/:id/members',authenticate,authorize('Administrator','Research Manager'),validate(z.object({userId:z.string().uuid(),memberRole:z.enum(['Lead','Contributor','Reviewer']).default('Contributor')})),async(req,res,next)=>{try{await transaction(async client=>{await client.query('INSERT INTO assignment_members(assignment_id,user_id,member_role) VALUES($1,$2,$3) ON CONFLICT(assignment_id,user_id) DO UPDATE SET member_role=EXCLUDED.member_role',[req.params.id,req.validated.userId,req.validated.memberRole]);await client.query('INSERT INTO assignment_history(assignment_id,user_id,action,details) VALUES($1,$2,$3,$4)',[req.params.id,req.user.id,'MEMBER_ASSIGNED',JSON.stringify(req.validated)])});res.status(204).end()}catch(error){next(error)}})
app.get('/api/assignments/:id/comments',authenticate,async(req,res,next)=>{try{const result=await query('SELECT c.id,c.body,c.created_at,u.id author_id,u.name author_name FROM assignment_comments c JOIN users u ON u.id=c.author_id WHERE c.assignment_id=$1 ORDER BY c.created_at',[req.params.id]);res.json(result.rows)}catch(error){next(error)}})
app.post('/api/assignments/:id/comments',authenticate,validate(z.object({body:z.string().min(1).max(4000)})),async(req,res,next)=>{try{if(!await canAccessAssignment(req.user,req.params.id))return res.status(403).json({error:'You cannot comment on this assignment.'});const result=await transaction(async client=>{const created=(await client.query('INSERT INTO assignment_comments(assignment_id,author_id,body) VALUES($1,$2,$3) RETURNING *',[req.params.id,req.user.id,req.validated.body])).rows[0];await client.query('INSERT INTO assignment_history(assignment_id,user_id,action,details) VALUES($1,$2,$3,$4)',[req.params.id,req.user.id,'COMMENTED',JSON.stringify({commentId:created.id})]);return created});res.status(201).json(result)}catch(error){next(error)}})
app.get('/api/assignments/:id/history',authenticate,async(req,res,next)=>{try{if(!await canAccessAssignment(req.user,req.params.id))return res.status(403).json({error:'You cannot view this assignment.'});res.json((await query('SELECT h.id,h.action,h.details,h.created_at,u.name user_name FROM assignment_history h LEFT JOIN users u ON u.id=h.user_id WHERE h.assignment_id=$1 ORDER BY h.created_at DESC',[req.params.id])).rows)}catch(error){next(error)}})
app.get('/api/assignments/:id/attachments',authenticate,async(req,res,next)=>{try{if(!await canAccessAssignment(req.user,req.params.id))return res.status(403).json({error:'You cannot view this assignment.'});res.json((await query('SELECT a.id,a.original_name,a.mime_type,a.size_bytes,a.created_at,u.name uploader_name FROM assignment_attachments a JOIN users u ON u.id=a.uploader_id WHERE a.assignment_id=$1 ORDER BY a.created_at DESC',[req.params.id])).rows)}catch(error){next(error)}})
app.post('/api/assignments/:id/attachments',authenticate,async(req,res,next)=>{try{if(!await canAccessAssignment(req.user,req.params.id))return res.status(403).json({error:'You cannot attach files to this assignment.'});let submittedName=String(req.headers['x-file-name']||'attachment.bin');try{submittedName=decodeURIComponent(submittedName)}catch{}const originalName=path.basename(submittedName).slice(0,255);if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({error:'Choose a non-empty file to upload.'});const storedName=`${crypto.randomUUID()}${path.extname(originalName).slice(0,12)}`;const uploadDir=path.resolve(config.uploadDir);await fs.mkdir(uploadDir,{recursive:true});await fs.writeFile(path.join(uploadDir,storedName),req.body,{flag:'wx'});const created=await transaction(async client=>{const row=(await client.query('INSERT INTO assignment_attachments(assignment_id,uploader_id,original_name,stored_name,mime_type,size_bytes) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,original_name,mime_type,size_bytes,created_at',[req.params.id,req.user.id,originalName,storedName,String(req.headers['x-file-type']||'application/octet-stream').slice(0,160),req.body.length])).rows[0];await client.query('INSERT INTO assignment_history(assignment_id,user_id,action,details) VALUES($1,$2,$3,$4)',[req.params.id,req.user.id,'FILE_ATTACHED',JSON.stringify({attachmentId:row.id,name:originalName})]);return row});res.status(201).json(created)}catch(error){next(error)}})
app.get('/api/attachments/:id/download',authenticate,async(req,res,next)=>{try{const attachment=(await query('SELECT * FROM assignment_attachments WHERE id=$1',[req.params.id])).rows[0];if(!attachment)return res.status(404).json({error:'Attachment not found.'});if(!await canAccessAssignment(req.user,attachment.assignment_id))return res.status(403).json({error:'You cannot download this file.'});res.setHeader('Content-Type',attachment.mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(attachment.original_name)}`);res.sendFile(path.resolve(config.uploadDir,attachment.stored_name))}catch(error){next(error)}})

app.get('/api/knowledge',authenticate,async(req,res,next)=>{try{const search=String(req.query.search||'').trim();const category=String(req.query.category||'').trim();const status=String(req.query.status||'').trim();const privileged=canReviewKnowledge(req.user);const result=await query(`SELECT k.*,u.name created_by_name,approver.name approved_by_name,COALESCE((SELECT json_agg(json_build_object('id',a.id,'title',a.title)) FROM knowledge_assignment_links l JOIN assignments a ON a.id=l.assignment_id WHERE l.knowledge_id=k.id),'[]') assignments,(SELECT COUNT(*)::int FROM knowledge_downloads d WHERE d.knowledge_id=k.id) download_count FROM knowledge_items k JOIN users u ON u.id=k.created_by LEFT JOIN users approver ON approver.id=k.approved_by WHERE($1::boolean OR k.status='Published' OR k.created_by=$2)AND($3='' OR k.category=$3)AND($4='' OR k.status=$4)AND($5='' OR to_tsvector('english',k.title||' '||k.description||' '||COALESCE(k.author,''))@@plainto_tsquery('english',$5) OR $5=ANY(k.tags)) ORDER BY k.updated_at DESC`,[privileged,req.user.id,category,status,search]);res.json(result.rows)}catch(error){next(error)}})
app.post('/api/knowledge',authenticate,async(req,res,next)=>{let storedPath;try{if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({error:'Choose a non-empty file to upload.'});let submittedName=String(req.headers['x-file-name']||'document.bin');try{submittedName=decodeURIComponent(submittedName)}catch{}const originalName=path.basename(submittedName).slice(0,255);const parsed=knowledgeSchema.safeParse({title:String(req.headers['x-title']||''),description:String(req.headers['x-description']||''),category:String(req.headers['x-category']||''),tags:String(req.headers['x-tags']||'').split(',').map(tag=>tag.trim()).filter(Boolean),author:req.headers['x-author']?String(req.headers['x-author']):null,documentDate:req.headers['x-document-date']?String(req.headers['x-document-date']):null});if(!parsed.success)return res.status(400).json({error:'Please correct the document metadata.',details:parsed.error.flatten()});const assignmentId=req.headers['x-assignment-id']?String(req.headers['x-assignment-id']):null;if(assignmentId&&!z.string().uuid().safeParse(assignmentId).success)return res.status(400).json({error:'The linked assignment is invalid.'});if(assignmentId&&!canManageKnowledge(req.user)&&!await canAccessAssignment(req.user,assignmentId))return res.status(403).json({error:'You cannot link this assignment.'});const storedName=`knowledge-${crypto.randomUUID()}${path.extname(originalName).slice(0,12)}`;const uploadDir=path.resolve(config.uploadDir);await fs.mkdir(uploadDir,{recursive:true});storedPath=path.join(uploadDir,storedName);await fs.writeFile(storedPath,req.body,{flag:'wx'});const {title,description,category,tags,author,documentDate}=parsed.data;const created=await transaction(async client=>{const item=(await client.query('INSERT INTO knowledge_items(title,description,category,tags,author,document_date,created_by,current_version) VALUES($1,$2,$3,$4,$5,$6,$7,1) RETURNING *',[title,description,category,[...new Set(tags)],author||null,documentDate||null,req.user.id])).rows[0];const version=(await client.query('INSERT INTO knowledge_versions(knowledge_id,version_number,uploader_id,original_name,stored_name,mime_type,size_bytes) VALUES($1,1,$2,$3,$4,$5,$6) RETURNING id,version_number,original_name,mime_type,size_bytes,notes,created_at',[item.id,req.user.id,originalName,storedName,String(req.headers['x-file-type']||'application/octet-stream').slice(0,160),req.body.length])).rows[0];if(assignmentId)await client.query('INSERT INTO knowledge_assignment_links(knowledge_id,assignment_id,linked_by) VALUES($1,$2,$3)',[item.id,assignmentId,req.user.id]);await audit(client,req.user.id,'KNOWLEDGE_CREATED','knowledge',item.id,{title,category,version:1,assignmentId});return {...item,version}});res.status(201).json(created)}catch(error){if(storedPath)await fs.unlink(storedPath).catch(()=>{});next(error)}})
app.patch('/api/knowledge/:id',authenticate,validate(knowledgeSchema),async(req,res,next)=>{try{const existing=(await query('SELECT * FROM knowledge_items WHERE id=$1',[req.params.id])).rows[0];if(!existing)return res.status(404).json({error:'Knowledge item not found.'});if(!canManageKnowledge(req.user)&&existing.created_by!==req.user.id)return res.status(403).json({error:'You cannot edit this knowledge item.'});if(existing.status==='Published'&&!canManageKnowledge(req.user))return res.status(403).json({error:'Only a manager can edit published knowledge.'});const {title,description,category,tags,author,documentDate}=req.validated;const updated=await transaction(async client=>{const row=(await client.query('UPDATE knowledge_items SET title=$1,description=$2,category=$3,tags=$4,author=$5,document_date=$6,updated_at=NOW() WHERE id=$7 RETURNING *',[title,description,category,[...new Set(tags.map(tag=>tag.trim()))],author||null,documentDate||null,req.params.id])).rows[0];await audit(client,req.user.id,'KNOWLEDGE_UPDATED','knowledge',req.params.id,{title,category});return row});res.json(updated)}catch(error){next(error)}})
app.post('/api/knowledge/:id/versions',authenticate,async(req,res,next)=>{let storedPath;try{const item=(await query('SELECT * FROM knowledge_items WHERE id=$1',[req.params.id])).rows[0];if(!item)return res.status(404).json({error:'Knowledge item not found.'});if(!canManageKnowledge(req.user)&&item.created_by!==req.user.id)return res.status(403).json({error:'You cannot upload a version for this item.'});if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({error:'Choose a non-empty file to upload.'});let submittedName=String(req.headers['x-file-name']||'document.bin');try{submittedName=decodeURIComponent(submittedName)}catch{}const originalName=path.basename(submittedName).slice(0,255);const storedName=`knowledge-${crypto.randomUUID()}${path.extname(originalName).slice(0,12)}`;const uploadDir=path.resolve(config.uploadDir);await fs.mkdir(uploadDir,{recursive:true});storedPath=path.join(uploadDir,storedName);await fs.writeFile(storedPath,req.body,{flag:'wx'});const created=await transaction(async client=>{const locked=(await client.query('SELECT current_version FROM knowledge_items WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];const number=locked.current_version+1;const row=(await client.query('INSERT INTO knowledge_versions(knowledge_id,version_number,uploader_id,original_name,stored_name,mime_type,size_bytes,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,version_number,original_name,mime_type,size_bytes,notes,created_at',[req.params.id,number,req.user.id,originalName,storedName,String(req.headers['x-file-type']||'application/octet-stream').slice(0,160),req.body.length,String(req.headers['x-version-notes']||'').slice(0,1000)])).rows[0];await client.query("UPDATE knowledge_items SET current_version=$1,status=CASE WHEN status='Published' THEN 'Draft' ELSE status END,approved_by=NULL,approved_at=NULL,updated_at=NOW() WHERE id=$2",[number,req.params.id]);await audit(client,req.user.id,'KNOWLEDGE_VERSION_UPLOADED','knowledge',req.params.id,{version:number,name:originalName});return row});res.status(201).json(created)}catch(error){if(storedPath)await fs.unlink(storedPath).catch(()=>{});next(error)}})
app.get('/api/knowledge/:id/versions',authenticate,async(req,res,next)=>{try{if(!await canReadKnowledge(req.user,req.params.id))return res.status(403).json({error:'You cannot view this knowledge item.'});res.json((await query('SELECT v.id,v.version_number,v.original_name,v.mime_type,v.size_bytes,v.notes,v.created_at,u.name uploader_name FROM knowledge_versions v JOIN users u ON u.id=v.uploader_id WHERE v.knowledge_id=$1 ORDER BY v.version_number DESC',[req.params.id])).rows)}catch(error){next(error)}})
app.get('/api/knowledge/versions/:versionId/download',authenticate,async(req,res,next)=>{try{const version=(await query('SELECT v.*,k.status,k.created_by FROM knowledge_versions v JOIN knowledge_items k ON k.id=v.knowledge_id WHERE v.id=$1',[req.params.versionId])).rows[0];if(!version)return res.status(404).json({error:'Document version not found.'});if(!await canReadKnowledge(req.user,version.knowledge_id))return res.status(403).json({error:'You cannot download this document.'});await transaction(async client=>{await client.query('INSERT INTO knowledge_downloads(knowledge_id,version_id,user_id) VALUES($1,$2,$3)',[version.knowledge_id,version.id,req.user.id]);await audit(client,req.user.id,'KNOWLEDGE_DOWNLOADED','knowledge',version.knowledge_id,{versionId:version.id,version:version.version_number})});res.setHeader('Content-Type',version.mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(version.original_name)}`);res.sendFile(path.resolve(config.uploadDir,version.stored_name))}catch(error){next(error)}})
app.patch('/api/knowledge/:id/status',authenticate,validate(z.object({status:z.enum(['Draft','Pending Approval','Published','Rejected','Archived']),reason:z.string().max(1000).optional()})),async(req,res,next)=>{try{const item=(await query('SELECT * FROM knowledge_items WHERE id=$1',[req.params.id])).rows[0];if(!item)return res.status(404).json({error:'Knowledge item not found.'});const target=req.validated.status;if(['Published','Rejected','Archived'].includes(target)&&!canReviewKnowledge(req.user))return res.status(403).json({error:'Only a reviewer or manager can approve, reject, or archive knowledge.'});if(['Draft','Pending Approval'].includes(target)&&!canManageKnowledge(req.user)&&item.created_by!==req.user.id)return res.status(403).json({error:'You cannot submit this knowledge item.'});if(target==='Published'&&item.current_version<1)return res.status(400).json({error:'Upload a document version before publishing.'});const updated=await transaction(async client=>{const approved=['Published','Archived'].includes(target);const row=(await client.query('UPDATE knowledge_items SET status=$1,approved_by=$2,approved_at=$3,rejection_reason=$4,updated_at=NOW() WHERE id=$5 RETURNING *',[target,approved?req.user.id:null,approved?new Date():null,target==='Rejected'?(req.validated.reason||'Not approved'):null,req.params.id])).rows[0];await audit(client,req.user.id,`KNOWLEDGE_${target.toUpperCase().replaceAll(' ','_')}`,'knowledge',req.params.id,{reason:req.validated.reason});return row});res.json(updated)}catch(error){next(error)}})
app.patch('/api/knowledge/:id/approve',authenticate,authorize('Administrator','Research Manager','Reviewer'),validate(z.object({approved:z.boolean().default(true),reason:z.string().max(1000).optional()})),async(req,res,next)=>{try{const target=req.validated.approved?'Published':'Rejected';const updated=await transaction(async client=>{const item=(await client.query('SELECT * FROM knowledge_items WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!item)return null;if(target==='Published'&&item.current_version<1)throw new Error('Upload a document version before publishing.');const row=(await client.query('UPDATE knowledge_items SET status=$1,approved_by=$2,approved_at=$3,rejection_reason=$4,updated_at=NOW() WHERE id=$5 RETURNING *',[target,target==='Published'?req.user.id:null,target==='Published'?new Date():null,target==='Rejected'?(req.validated.reason||'Not approved'):null,req.params.id])).rows[0];await audit(client,req.user.id,target==='Published'?'KNOWLEDGE_PUBLISHED':'KNOWLEDGE_REJECTED','knowledge',req.params.id,{reason:req.validated.reason});return row});if(!updated)return res.status(404).json({error:'Knowledge item not found.'});res.json(updated)}catch(error){next(error)}})
app.post('/api/knowledge/:id/assignments',authenticate,validate(z.object({assignmentId:z.string().uuid()})),async(req,res,next)=>{try{if(!canManageKnowledge(req.user)&&!await canAccessAssignment(req.user,req.validated.assignmentId))return res.status(403).json({error:'You cannot link this assignment.'});await transaction(async client=>{await client.query('INSERT INTO knowledge_assignment_links(knowledge_id,assignment_id,linked_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[req.params.id,req.validated.assignmentId,req.user.id]);await audit(client,req.user.id,'KNOWLEDGE_ASSIGNMENT_LINKED','knowledge',req.params.id,{assignmentId:req.validated.assignmentId})});res.status(204).end()}catch(error){next(error)}})
app.delete('/api/knowledge/:id/assignments/:assignmentId',authenticate,async(req,res,next)=>{try{if(!canManageKnowledge(req.user)&&!await canAccessAssignment(req.user,req.params.assignmentId))return res.status(403).json({error:'You cannot unlink this assignment.'});await transaction(async client=>{await client.query('DELETE FROM knowledge_assignment_links WHERE knowledge_id=$1 AND assignment_id=$2',[req.params.id,req.params.assignmentId]);await audit(client,req.user.id,'KNOWLEDGE_ASSIGNMENT_UNLINKED','knowledge',req.params.id,{assignmentId:req.params.assignmentId})});res.status(204).end()}catch(error){next(error)}})
app.get('/api/knowledge/:id/downloads',authenticate,authorize('Administrator','Research Manager'),async(req,res,next)=>{try{res.json((await query('SELECT d.id,d.downloaded_at,v.version_number,v.original_name,u.name user_name FROM knowledge_downloads d JOIN knowledge_versions v ON v.id=d.version_id JOIN users u ON u.id=d.user_id WHERE d.knowledge_id=$1 ORDER BY d.downloaded_at DESC',[req.params.id])).rows)}catch(error){next(error)}})

const noticeSchema=z.object({title:z.string().min(3).max(200),body:z.string().min(3).max(4000),severity:z.enum(['Information','Important','Urgent']).default('Information'),audienceRole:z.enum(roles).nullable().default(null),eventStart:z.string().datetime().nullable().default(null),eventEnd:z.string().datetime().nullable().default(null)})
app.get('/api/alerts',authenticate,async(req,res,next)=>{try{const manager=['Administrator','Research Manager'].includes(req.user.role);const result=await query(`SELECT a.*,u.name created_by_name,r.name reviewed_by_name FROM alerts a JOIN users u ON u.id=a.created_by LEFT JOIN users r ON r.id=a.reviewed_by WHERE(($1 AND TRUE)OR a.status='Published' OR a.created_by=$2)AND(a.audience_role IS NULL OR a.audience_role=$3 OR a.created_by=$2)AND(a.expires_at IS NULL OR a.expires_at>NOW() OR a.created_by=$2) ORDER BY CASE a.status WHEN 'Pending Approval' THEN 0 WHEN 'Published' THEN 1 ELSE 2 END,a.created_at DESC`,[manager,req.user.id,req.user.role]);res.json(result.rows)}catch(error){next(error)}})
app.post('/api/alerts',authenticate,validate(noticeSchema),async(req,res,next)=>{try{const v=req.validated;const created=await transaction(async client=>{const row=(await client.query("INSERT INTO alerts(title,body,severity,audience_role,event_start,event_end,created_by,status)VALUES($1,$2,$3,$4,$5,$6,$7,'Pending Approval')RETURNING *",[v.title.trim(),v.body.trim(),v.severity,v.audienceRole,v.eventStart,v.eventEnd,req.user.id])).rows[0];await client.query("INSERT INTO notifications(user_id,title,body,entity_type,entity_id)SELECT id,'Notice awaiting approval',$1,'notice',$2 FROM users WHERE active=TRUE AND role IN('Administrator','Research Manager')",[`“${row.title}” was submitted by ${req.user.name}.`,row.id]);await audit(client,req.user.id,'NOTICE_SUBMITTED','notice',row.id,{title:row.title});return row});res.status(201).json(created)}catch(error){next(error)}})
app.patch('/api/alerts/:id/review',authenticate,authorize('Administrator','Research Manager'),validate(z.object({approved:z.boolean(),reason:z.string().max(1000).default('')})),async(req,res,next)=>{try{const result=await transaction(async client=>{const row=(await client.query("UPDATE alerts SET status=$1,reviewed_by=$2,reviewed_at=NOW(),rejection_reason=$3 WHERE id=$4 AND status='Pending Approval' RETURNING *",[req.validated.approved?'Published':'Rejected',req.user.id,req.validated.approved?null:req.validated.reason.trim(),req.params.id])).rows[0];if(!row)return null;await client.query('INSERT INTO notifications(user_id,title,body,entity_type,entity_id)VALUES($1,$2,$3,$4,$5)',[row.created_by,req.validated.approved?'Notice approved':'Notice returned for correction',req.validated.approved?`“${row.title}” is now published on the Notice Board.`:`“${row.title}” was not approved: ${req.validated.reason||'No reason supplied.'}`,'notice',row.id]);if(req.validated.approved)await client.query("INSERT INTO notifications(user_id,title,body,entity_type,entity_id)SELECT id,'New Notice Board post',$1,'notice',$2 FROM users WHERE active=TRUE AND id<>$3",[`“${row.title}” has been published.`,row.id,row.created_by]);await audit(client,req.user.id,req.validated.approved?'NOTICE_APPROVED':'NOTICE_REJECTED','notice',row.id,{reason:req.validated.reason});return row});if(!result)return res.status(404).json({error:'Pending notice not found.'});res.json(result)}catch(error){next(error)}})
app.get('/api/calendar',authenticate,async(req,res,next)=>{try{const [assignments,notices]=await Promise.all([query(`SELECT a.id,a.title,a.due_date start_at,'assignment' type,a.status FROM assignments a WHERE a.due_date IS NOT NULL AND($1 OR a.created_by=$2 OR EXISTS(SELECT 1 FROM assignment_members am WHERE am.assignment_id=a.id AND am.user_id=$2)) ORDER BY a.due_date`,[['Administrator','Research Manager'].includes(req.user.role),req.user.id]),query("SELECT id,title,event_start start_at,event_end end_at,'notice' type,severity status FROM alerts WHERE status='Published' AND event_start IS NOT NULL AND(audience_role IS NULL OR audience_role=$1) ORDER BY event_start",[req.user.role])]);res.json([...assignments.rows,...notices.rows].sort((a,b)=>new Date(a.start_at)-new Date(b.start_at)))}catch(error){next(error)}})
app.get('/api/analytics/reports',authenticate,authorize('Administrator','Research Manager'),async(req,res,next)=>{
  try{
    const filters=z.object({from:z.string().optional().default(''),to:z.string().optional().default(''),division:z.string().max(160).optional().default(''),status:z.string().max(40).optional().default('')}).parse({from:String(req.query.from||''),to:String(req.query.to||''),division:String(req.query.division||''),status:String(req.query.status||'')})
    const values=[filters.from||null,filters.to||null,filters.division,filters.status]
    const where="($1::date IS NULL OR a.created_at::date>=$1::date)AND($2::date IS NULL OR a.created_at::date<=$2::date)AND($3='' OR a.division=$3)AND($4='' OR a.status=$4)"
    const [summary,assignmentStatuses,divisions,documents,research,reviewers,trends,people]=await Promise.all([
      query(`SELECT COUNT(*)::int total,COUNT(*)FILTER(WHERE a.status='Completed')::int completed,COUNT(*)FILTER(WHERE a.status='Overdue' OR(a.due_date<CURRENT_DATE AND a.status!='Completed'))::int overdue,ROUND(COALESCE(100.0*COUNT(*)FILTER(WHERE a.status='Completed')/NULLIF(COUNT(*),0),0),1)::float completion_rate FROM assignments a WHERE ${where}`,values),
      query(`SELECT a.status,COUNT(*)::int total FROM assignments a WHERE ${where} GROUP BY a.status ORDER BY total DESC`,values),
      query(`SELECT a.division,COUNT(*)::int total,COUNT(*)FILTER(WHERE a.status='Completed')::int completed FROM assignments a WHERE ${where} GROUP BY a.division ORDER BY total DESC`,values),
      query("SELECT k.status,COUNT(*)::int total FROM knowledge_items k WHERE($1::date IS NULL OR k.created_at::date>=$1::date)AND($2::date IS NULL OR k.created_at::date<=$2::date)GROUP BY k.status ORDER BY total DESC",values.slice(0,2)),
      query("SELECT p.status,COUNT(*)::int total FROM research_projects p WHERE($1::date IS NULL OR p.created_at::date>=$1::date)AND($2::date IS NULL OR p.created_at::date<=$2::date)GROUP BY p.status ORDER BY total DESC",values.slice(0,2)),
      query("SELECT u.id,u.name,(SELECT COUNT(*)::int FROM document_reviews r WHERE r.actor_id=u.id AND r.action='APPROVED' AND($1::date IS NULL OR r.created_at::date>=$1::date)AND($2::date IS NULL OR r.created_at::date<=$2::date))approved,(SELECT COUNT(*)::int FROM document_reviews r WHERE r.actor_id=u.id AND r.action='REJECTED' AND($1::date IS NULL OR r.created_at::date>=$1::date)AND($2::date IS NULL OR r.created_at::date<=$2::date))rejected,(SELECT COUNT(*)::int FROM knowledge_items k WHERE k.reviewer_id=u.id AND k.status='Pending Approval')pending FROM users u WHERE u.role IN('Reviewer','Research Manager')ORDER BY pending DESC,approved DESC",values.slice(0,2)),
      query("SELECT TO_CHAR(DATE_TRUNC('month',a.created_at),'Mon YYYY') AS month_label,DATE_TRUNC('month',a.created_at) AS bucket,COUNT(*)::int AS created,COUNT(*)FILTER(WHERE a.status='Completed')::int AS completed FROM assignments a WHERE a.created_at>=DATE_TRUNC('month',CURRENT_DATE)-INTERVAL '5 months' GROUP BY DATE_TRUNC('month',a.created_at) ORDER BY bucket"),
      query(`SELECT u.id,u.name,u.role,u.division,COUNT(a.id)::int assigned,COUNT(a.id)FILTER(WHERE a.status='Completed')::int completed,COUNT(a.id)FILTER(WHERE a.status='Overdue' OR(a.due_date<CURRENT_DATE AND a.status!='Completed'))::int overdue,ROUND(COALESCE(100.0*COUNT(a.id)FILTER(WHERE a.status='Completed')/NULLIF(COUNT(a.id),0),0),1)::float completion_rate FROM users u LEFT JOIN assignment_members am ON am.user_id=u.id LEFT JOIN assignments a ON a.id=am.assignment_id AND($1::date IS NULL OR a.created_at::date>=$1::date)AND($2::date IS NULL OR a.created_at::date<=$2::date)AND($3='' OR a.division=$3)AND($4='' OR a.status=$4) WHERE u.active=TRUE GROUP BY u.id ORDER BY completion_rate DESC,completed DESC,u.name`,values)
    ])
    const documentTotals=documents.rows.reduce((acc,row)=>({...acc,[row.status]:row.total}),{})
    const researchTotals=research.rows.reduce((acc,row)=>({...acc,[row.status]:row.total}),{})
    res.json({filters,summary:{...summary.rows[0],pending_reviews:documentTotals['Pending Approval']||0,published_documents:documentTotals.Published||0,active_research:(researchTotals.Active||0)+(researchTotals['Under Review']||0)},assignmentStatuses:assignmentStatuses.rows,divisions:divisions.rows,documentStatuses:documents.rows,researchStatuses:research.rows,reviewers:reviewers.rows,trends:trends.rows.map(row=>({...row,month:row.month_label})),people:people.rows})
  }catch(error){next(error)}
})
app.get('/api/analytics/overview',authenticate,authorize('Administrator','Research Manager'),async(_req,res,next)=>{try{const [statuses,workloads,members]=await Promise.all([query('SELECT status,COUNT(*)::int total FROM assignments GROUP BY status'),query(`SELECT u.id,u.name,COUNT(am.assignment_id) FILTER(WHERE a.status!='Completed')::int active FROM users u LEFT JOIN assignment_members am ON am.user_id=u.id LEFT JOIN assignments a ON a.id=am.assignment_id GROUP BY u.id ORDER BY active DESC`),query('SELECT role,COUNT(*)::int total FROM users WHERE active=TRUE GROUP BY role')]);res.json({assignmentStatuses:statuses.rows,workloads:workloads.rows,membersByRole:members.rows})}catch(error){next(error)}})
const researchSchema=z.object({title:z.string().min(4).max(240),summary:z.string().max(6000).default(''),researchQuestion:z.string().max(3000).default(''),objectives:z.string().max(5000).default(''),methodology:z.string().max(5000).default(''),startDate:z.string().nullable().optional(),endDate:z.string().nullable().optional(),assignmentId:z.string().uuid().nullable().optional(),collaboratorIds:z.array(z.string().uuid()).default([]),knowledgeIds:z.array(z.string().uuid()).default([])})
app.get('/api/research',authenticate,async(req,res,next)=>{try{const all=['Administrator','Research Manager','Reviewer'].includes(req.user.role);res.json((await query(`SELECT p.*,u.name lead_name,COALESCE(json_agg(DISTINCT jsonb_build_object('id',c.id,'name',c.name,'role',rc.role))FILTER(WHERE c.id IS NOT NULL),'[]') collaborators,COALESCE(json_agg(DISTINCT jsonb_build_object('id',m.id,'title',m.title,'due_date',m.due_date,'status',m.status))FILTER(WHERE m.id IS NOT NULL),'[]') milestones FROM research_projects p JOIN users u ON u.id=p.lead_id LEFT JOIN research_collaborators rc ON rc.project_id=p.id LEFT JOIN users c ON c.id=rc.user_id LEFT JOIN research_milestones m ON m.project_id=p.id WHERE $1 OR p.lead_id=$2 OR rc.user_id=$2 GROUP BY p.id,u.name ORDER BY p.updated_at DESC`,[all,req.user.id])).rows)}catch(error){next(error)}})
app.post('/api/research',authenticate,authorize('Administrator','Research Manager'),validate(researchSchema),async(req,res,next)=>{try{const created=await transaction(async client=>{const v=req.validated;const p=(await client.query('INSERT INTO research_projects(title,summary,research_question,objectives,methodology,start_date,end_date,lead_id,assignment_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[v.title,v.summary,v.researchQuestion,v.objectives,v.methodology,v.startDate||null,v.endDate||null,req.user.id,v.assignmentId||null])).rows[0];for(const id of v.collaboratorIds)await client.query('INSERT INTO research_collaborators(project_id,user_id)VALUES($1,$2)ON CONFLICT DO NOTHING',[p.id,id]);for(const id of v.knowledgeIds)await client.query('INSERT INTO research_knowledge_links(project_id,knowledge_item_id)VALUES($1,$2)ON CONFLICT DO NOTHING',[p.id,id]);return p});res.status(201).json(created)}catch(error){next(error)}})
app.patch('/api/research/:id/status',authenticate,validate(z.object({status:z.enum(['Planning','Active','Under Review','Completed','Archived'])})),async(req,res,next)=>{
  try{
    const project=(await query('SELECT lead_id FROM research_projects WHERE id=$1',[req.params.id])).rows[0]
    if(!project)return res.status(404).json({error:'Research project not found.'})
    const isManager=['Administrator','Research Manager'].includes(req.user.role)
    const isParticipant=project.lead_id===req.user.id||(await query('SELECT 1 FROM research_collaborators WHERE project_id=$1 AND user_id=$2',[req.params.id,req.user.id])).rowCount>0
    if(!isManager&&!isParticipant)return res.status(403).json({error:'You are not authorized to update this research project.'})
    if(req.validated.status==='Completed'&&!['Administrator','Research Manager','Reviewer'].includes(req.user.role))return res.status(403).json({error:'Only a reviewer or manager can approve completed research.'})
    const row=(await query('UPDATE research_projects SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.validated.status,req.params.id])).rows[0]
    res.json(row)
  }catch(error){next(error)}
})
app.post('/api/research/:id/milestones',authenticate,validate(z.object({title:z.string().min(3).max(200),dueDate:z.string().nullable().optional()})),async(req,res,next)=>{try{res.status(201).json((await query('INSERT INTO research_milestones(project_id,title,due_date)VALUES($1,$2,$3)RETURNING *',[req.params.id,req.validated.title,req.validated.dueDate||null])).rows[0])}catch(error){next(error)}})
app.get('/api/audit-logs',authenticate,authorize('Administrator'),async(req,res,next)=>{
  try{
    const filters=z.object({search:z.string().max(200).default(''),userId:z.string().uuid().or(z.literal('')).default(''),action:z.string().max(100).default(''),entityType:z.string().max(80).default(''),from:z.string().default(''),to:z.string().default(''),limit:z.coerce.number().int().min(1).max(500).default(250)}).parse({search:String(req.query.search||''),userId:String(req.query.userId||''),action:String(req.query.action||''),entityType:String(req.query.entityType||''),from:String(req.query.from||''),to:String(req.query.to||''),limit:req.query.limit||250})
    const values=[filters.search,filters.userId||null,filters.action,filters.entityType,filters.from||null,filters.to||null,filters.limit]
    const where="($1='' OR l.action ILIKE '%'||$1||'%' OR l.entity_type ILIKE '%'||$1||'%' OR COALESCE(u.name,'System') ILIKE '%'||$1||'%' OR l.details::text ILIKE '%'||$1||'%')AND($2::uuid IS NULL OR l.user_id=$2)AND($3='' OR l.action=$3)AND($4='' OR l.entity_type=$4)AND($5::date IS NULL OR l.created_at::date>=$5::date)AND($6::date IS NULL OR l.created_at::date<=$6::date)"
    const [items,total,actions,entities]=await Promise.all([
      query(`SELECT l.*,COALESCE(u.name,'System / Unknown')user_name,u.email user_email FROM audit_logs l LEFT JOIN users u ON u.id=l.user_id WHERE ${where} ORDER BY l.created_at DESC LIMIT $7`,values),
      query(`SELECT COUNT(*)::int total FROM audit_logs l LEFT JOIN users u ON u.id=l.user_id WHERE ${where}`,values.slice(0,6)),
      query('SELECT DISTINCT action FROM audit_logs ORDER BY action'),
      query('SELECT DISTINCT entity_type FROM audit_logs ORDER BY entity_type')
    ])
    res.json({items:items.rows,total:total.rows[0].total,actions:actions.rows.map(row=>row.action),entityTypes:entities.rows.map(row=>row.entity_type)})
  }catch(error){next(error)}
})
app.post('/api/document-reviews/:id/submit',authenticate,async(req,res,next)=>{try{const updated=await transaction(async client=>{const item=(await client.query("UPDATE knowledge_items SET status='Pending Approval',approved_by=NULL,approved_at=NULL,rejection_reason=NULL,updated_at=NOW() WHERE id=$1 AND(created_by=$2 OR $3) RETURNING *",[req.params.id,req.user.id,canManageKnowledge(req.user)])).rows[0];if(!item)return null;await client.query("INSERT INTO document_reviews(knowledge_id,reviewer_id,actor_id,action,comments) VALUES($1,$2,$3,$4,'Submitted for review')",[item.id,item.reviewer_id,req.user.id,item.reviewer_id?'RESUBMITTED':'SUBMITTED']);await client.query("INSERT INTO notifications(user_id,title,body,entity_type,entity_id) SELECT id,'Document awaiting review',$1,'knowledge',$2 FROM users WHERE active=TRUE AND role IN('Reviewer','Research Manager') AND($3::uuid IS NULL OR id=$3)",[`“${item.title}” has been submitted for review.`,item.id,item.reviewer_id||null]);await audit(client,req.user.id,'DOCUMENT_SUBMITTED','knowledge',item.id,{});return item});if(!updated)return res.status(404).json({error:'Document not found or you cannot submit it.'});res.json(updated)}catch(error){next(error)}})
app.get('/api/document-reviews',authenticate,authorize('Administrator','Research Manager','Reviewer'),async(req,res,next)=>{try{const mine=req.user.role==='Reviewer';res.json((await query(`SELECT k.*,creator.name created_by_name,reviewer.name reviewer_name,COALESCE((SELECT json_agg(json_build_object('id',r.id,'action',r.action,'comments',r.comments,'created_at',r.created_at,'actor_name',actor.name) ORDER BY r.created_at DESC) FROM document_reviews r JOIN users actor ON actor.id=r.actor_id WHERE r.knowledge_id=k.id),'[]') review_history FROM knowledge_items k JOIN users creator ON creator.id=k.created_by LEFT JOIN users reviewer ON reviewer.id=k.reviewer_id WHERE k.status='Pending Approval' AND(NOT $1::boolean OR k.reviewer_id IS NULL OR k.reviewer_id=$2) ORDER BY k.updated_at`,[mine,req.user.id])).rows)}catch(error){next(error)}})
app.patch('/api/document-reviews/:id/assign',authenticate,authorize('Administrator','Research Manager'),validate(z.object({reviewerId:z.string().uuid()})),async(req,res,next)=>{try{const updated=await transaction(async client=>{const reviewer=(await client.query("SELECT id,name FROM users WHERE id=$1 AND role IN('Reviewer','Research Manager','Administrator') AND active=TRUE",[req.validated.reviewerId])).rows[0];if(!reviewer)throw new Error('Choose an active reviewer or manager.');const item=(await client.query("UPDATE knowledge_items SET reviewer_id=$1,status='Pending Approval',updated_at=NOW() WHERE id=$2 RETURNING *",[reviewer.id,req.params.id])).rows[0];if(!item)return null;await client.query("INSERT INTO document_reviews(knowledge_id,reviewer_id,actor_id,action,comments) VALUES($1,$2,$3,'ASSIGNED',$4)",[item.id,reviewer.id,req.user.id,`Assigned to ${reviewer.name}`]);await client.query("INSERT INTO notifications(user_id,title,body,entity_type,entity_id) VALUES($1,'Document review assigned',$2,'knowledge',$3)",[reviewer.id,`You have been assigned to review “${item.title}”.`,item.id]);await audit(client,req.user.id,'DOCUMENT_REVIEW_ASSIGNED','knowledge',item.id,{reviewerId:reviewer.id});return {...item,reviewer_name:reviewer.name}});if(!updated)return res.status(404).json({error:'Document not found.'});res.json(updated)}catch(error){next(error)}})
app.post('/api/document-reviews/:id/decision',authenticate,authorize('Administrator','Research Manager','Reviewer'),validate(z.object({approved:z.boolean(),comments:z.string().max(2000).default('')})),async(req,res,next)=>{
  try{
    if(!req.validated.approved&&!req.validated.comments.trim())return res.status(400).json({error:'Explain what must be corrected before rejecting.'})
    const result=await transaction(async client=>{
      const item=(await client.query('SELECT * FROM knowledge_items WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0]
      if(!item)return {kind:'missing'}
      if(item.status!=='Pending Approval')return {kind:'conflict'}
      if(req.user.role==='Reviewer'&&item.reviewer_id&&item.reviewer_id!==req.user.id)return {kind:'forbidden'}
      const status=req.validated.approved?'Published':'Rejected'
      const row=(await client.query('UPDATE knowledge_items SET status=$1,approved_by=$2,approved_at=$3,rejection_reason=$4,updated_at=NOW() WHERE id=$5 RETURNING *',[status,req.validated.approved?req.user.id:null,req.validated.approved?new Date():null,req.validated.approved?null:req.validated.comments,item.id])).rows[0]
      await client.query('INSERT INTO document_reviews(knowledge_id,reviewer_id,actor_id,action,comments) VALUES($1,$2,$3,$4,$5)',[item.id,item.reviewer_id,req.user.id,req.validated.approved?'APPROVED':'REJECTED',req.validated.comments])
      await client.query('INSERT INTO notifications(user_id,title,body,entity_type,entity_id) VALUES($1,$2,$3,$4,$5)',[item.created_by,req.validated.approved?'Document approved':'Document returned for correction',req.validated.approved?`“${item.title}” has been approved and published.`:`“${item.title}” was rejected: ${req.validated.comments}`,'knowledge',item.id])
      await audit(client,req.user.id,req.validated.approved?'KNOWLEDGE_PUBLISHED':'KNOWLEDGE_REJECTED','knowledge',item.id,{comments:req.validated.comments})
      return {kind:'updated',row}
    })
    if(result.kind==='missing')return res.status(404).json({error:'Document not found.'})
    if(result.kind==='conflict')return res.status(409).json({error:'Only pending documents can be reviewed.'})
    if(result.kind==='forbidden')return res.status(403).json({error:'This review is assigned to another reviewer.'})
    res.json(result.row)
  }catch(error){next(error)}
})
app.get('/api/document-reviews/:id/history',authenticate,async(req,res,next)=>{try{if(!await canReadKnowledge(req.user,req.params.id))return res.status(403).json({error:'You cannot view this review history.'});res.json((await query('SELECT r.id,r.action,r.comments,r.created_at,actor.name actor_name,reviewer.name reviewer_name FROM document_reviews r JOIN users actor ON actor.id=r.actor_id LEFT JOIN users reviewer ON reviewer.id=r.reviewer_id WHERE r.knowledge_id=$1 ORDER BY r.created_at DESC',[req.params.id])).rows)}catch(error){next(error)}})
app.get('/api/notifications',authenticate,async(req,res,next)=>{try{res.json((await query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id])).rows)}catch(error){next(error)}})
app.patch('/api/notifications/:id/read',authenticate,async(req,res,next)=>{try{const row=(await query('UPDATE notifications SET read_at=COALESCE(read_at,NOW()) WHERE id=$1 AND user_id=$2 RETURNING *',[req.params.id,req.user.id])).rows[0];if(!row)return res.status(404).json({error:'Notification not found.'});res.json(row)}catch(error){next(error)}})
app.get('/api/documents',authenticate,async(req,res,next)=>{try{res.json((await query(`SELECT k.*,u.name created_by_name,l.locked_at,l.expires_at,lu.name locked_by_name FROM knowledge_items k JOIN users u ON u.id=k.created_by LEFT JOIN document_locks l ON l.knowledge_id=k.id AND l.expires_at>NOW() LEFT JOIN users lu ON lu.id=l.locked_by WHERE k.status='Published' OR k.created_by=$1 OR $2 ORDER BY k.updated_at DESC`,[req.user.id,['Administrator','Research Manager','Reviewer'].includes(req.user.role)])).rows)}catch(error){next(error)}})
app.post('/api/documents/:id/checkout',authenticate,async(req,res,next)=>{try{const row=(await query(`INSERT INTO document_locks(knowledge_id,locked_by)VALUES($1,$2)ON CONFLICT(knowledge_id)DO UPDATE SET locked_by=EXCLUDED.locked_by,locked_at=NOW(),expires_at=NOW()+INTERVAL '2 hours' WHERE document_locks.expires_at<NOW() OR document_locks.locked_by=$2 RETURNING *`,[req.params.id,req.user.id])).rows[0];if(!row)return res.status(409).json({error:'This document is checked out by another user.'});res.json(row)}catch(error){next(error)}})
app.post('/api/documents/:id/checkin',authenticate,async(req,res,next)=>{try{const result=await query('DELETE FROM document_locks WHERE knowledge_id=$1 AND(locked_by=$2 OR $3)RETURNING *',[req.params.id,req.user.id,['Administrator','Research Manager'].includes(req.user.role)]);if(!result.rowCount)return res.status(403).json({error:'You do not hold this document lock.'});res.status(204).end()}catch(error){next(error)}})
app.patch('/api/documents/:id/retention',authenticate,authorize('Administrator','Research Manager'),validate(z.object({retentionUntil:z.string().nullable(),archive:z.boolean().default(false)})),async(req,res,next)=>{try{res.json((await query("UPDATE knowledge_items SET retention_until=$1,status=CASE WHEN $2 THEN 'Archived' ELSE status END,updated_at=NOW() WHERE id=$3 RETURNING *",[req.validated.retentionUntil,req.validated.archive,req.params.id])).rows[0])}catch(error){next(error)}})
app.get('/api/settings/email-status',authenticate,authorize('Administrator'),(_req,res)=>res.json(mailStatus()))
app.post('/api/settings/test-email',authenticate,authorize('Administrator'),validate(testEmailSchema),async(req,res,next)=>{try{const result=await sendMail({to:req.validated.email,subject:'PSC App2 email delivery test',text:`This test confirms that PSC App2 can deliver email notifications to ${req.validated.email}.`});await query("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details)VALUES($1,'TEST_EMAIL_SENT','settings','email',$2)",[req.user.id,JSON.stringify({recipient:req.validated.email,messageId:result.messageId})]);res.json({message:`Test email sent successfully to ${req.validated.email}.`,...result})}catch(error){next(error)}})
const systemSettingsSchema=z.object({organizationName:z.string().min(3).max(200),departmentName:z.string().min(3).max(200),supportEmail:z.string().email().max(255),sessionMinutes:z.number().int().min(15).max(1440),maxUploadMb:z.number().int().min(1).max(500),defaultRetentionDays:z.number().int().min(30).max(7300),documentCategories:z.array(z.string().min(2).max(100)).min(1).max(30),maintenanceMode:z.boolean(),emailNotifications:z.boolean()})
const preferenceSchema=z.object({emailNotifications:z.boolean(),inAppNotifications:z.boolean(),compactLayout:z.boolean(),themeMode:z.enum(['Dark','Light','System']),accentColor:z.enum(['Gold','Blue','Green'])})
app.get('/api/settings',authenticate,async(req,res,next)=>{try{const [system,preferences,health]=await Promise.all([query('SELECT organization_name,department_name,support_email,session_minutes,max_upload_mb,default_retention_days,document_categories,maintenance_mode,email_notifications,updated_at FROM system_settings WHERE id=1'),query('SELECT email_notifications,in_app_notifications,compact_layout,theme_mode,accent_color,updated_at FROM user_preferences WHERE user_id=$1',[req.user.id]),query('SELECT NOW() database_time')]);res.json({system:system.rows[0],preferences:preferences.rows[0]||{email_notifications:true,in_app_notifications:true,compact_layout:false,theme_mode:'Dark',accent_color:'Gold'},health:{api:'healthy',database:'connected',environment:config.environment,database_time:health.rows[0].database_time,configured_upload_limit_mb:config.maxUploadMb,configured_session:config.jwtExpiresIn}})}catch(error){next(error)}})
app.get('/api/settings/updates',authenticate,async(_req,res,next)=>{try{const database=await query('SELECT current_database() database,VERSION() version,NOW() checked_at');res.json({application:'PSC App2',applicationVersion:'0.1.0',apiVersion:'0.1.0',runtime:process.version,database:database.rows[0].database,databaseVersion:String(database.rows[0].version).split(' on ')[0],status:'Installed services healthy',updateChannel:'Manual / GitHub',automaticUpdates:false,checkedAt:database.rows[0].checked_at})}catch(error){next(error)}})
app.patch('/api/settings/system',authenticate,authorize('Administrator'),validate(systemSettingsSchema),async(req,res,next)=>{try{const v=req.validated;const updated=await transaction(async client=>{const row=(await client.query('UPDATE system_settings SET organization_name=$1,department_name=$2,support_email=$3,session_minutes=$4,max_upload_mb=$5,default_retention_days=$6,document_categories=$7,maintenance_mode=$8,email_notifications=$9,updated_by=$10,updated_at=NOW() WHERE id=1 RETURNING *',[v.organizationName,v.departmentName,v.supportEmail,v.sessionMinutes,v.maxUploadMb,v.defaultRetentionDays,[...new Set(v.documentCategories.map(value=>value.trim()))],v.maintenanceMode,v.emailNotifications,req.user.id])).rows[0];await audit(client,req.user.id,'SYSTEM_SETTINGS_UPDATED','settings','1',{maintenanceMode:v.maintenanceMode,sessionMinutes:v.sessionMinutes,maxUploadMb:v.maxUploadMb});return row});res.json(updated)}catch(error){next(error)}})
app.patch('/api/settings/preferences',authenticate,validate(preferenceSchema),async(req,res,next)=>{try{const v=req.validated;const row=(await query('INSERT INTO user_preferences(user_id,email_notifications,in_app_notifications,compact_layout,theme_mode,accent_color)VALUES($1,$2,$3,$4,$5,$6)ON CONFLICT(user_id)DO UPDATE SET email_notifications=$2,in_app_notifications=$3,compact_layout=$4,theme_mode=$5,accent_color=$6,updated_at=NOW()RETURNING *',[req.user.id,v.emailNotifications,v.inAppNotifications,v.compactLayout,v.themeMode,v.accentColor])).rows[0];res.json(row)}catch(error){next(error)}})

app.use((_req,res)=>res.status(404).json({error:'API endpoint not found.'}))
app.use((error,_req,res,_next)=>{console.error(error);res.status(500).json({error:config.environment==='production'?'The service could not complete your request.':error.message})})
export default app
