import { useState } from 'react'
import type { AiResearchEngine, AiResearchJob } from './api'

type Message={role:'assistant'|'user';text:string}
type Props={engine:AiResearchEngine|null;jobs:AiResearchJob[];onAsk:(question:string)=>Promise<string>}
export default function AIResearchChat({engine,jobs,onAsk}:Props){
  const [question,setQuestion]=useState('')
  const [sending,setSending]=useState(false)
  const [messages,setMessages]=useState<Message[]>([{role:'assistant',text:'Hello. I am the PSC AI Researcher. Ask me a research question, request an evidence plan, or define a policy topic to investigate. I will only support research work.'}])
  const send=async()=>{const text=question.trim();if(text.length<10||sending)return;setQuestion('');setMessages(current=>[...current,{role:'user',text}]);setSending(true);try{const answer=await onAsk(text);setMessages(current=>[...current,{role:'assistant',text:answer}])}catch(error){setMessages(current=>[...current,{role:'assistant',text:error instanceof Error?error.message:'The research request could not be prepared.'}])}finally{setSending(false)}}
  return <div className="ai-chat-layout"><section className="ai-chat"><header><div><strong>AI Research conversation</strong><small>Research questions only · Human review required</small></div><b className={engine?.ollamaConnected?'online':'offline'}>{engine?.ollamaConnected?'Local AI online':'Local AI offline'}</b></header><div className="ai-chat-messages">{messages.map((message,index)=><article className={message.role} key={index}><span>{message.role==='assistant'?'AI':'You'}</span><p>{message.text}</p></article>)}{sending&&<article className="assistant"><span>AI</span><p>Preparing a research plan…</p></article>}</div><div className="ai-chat-input"><textarea value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send()}}} placeholder="Ask a research question, e.g. What evidence should inform remote-work policy in Kenya's public service?"/><button onClick={send} disabled={question.trim().length<10||sending}>Send</button></div><small className="ai-chat-scope">This assistant cannot create assignments, manage users, approve records, or perform unrelated administrative actions.</small></section><aside className="ai-chat-history"><h3>Research history</h3>{jobs.slice(0,8).map(job=><article key={job.id}><span>{job.status}</span><strong>{job.title}</strong><small>{job.question}</small></article>)}{!jobs.length&&<p>No research conversations yet.</p>}</aside></div>
}
