import { useState } from 'react'
import type { AiResearchEngine, AiResearchJob, FelixAction, FelixResponse } from './api'

type Message={role:'assistant'|'user';text:string;references?:string[];action?:FelixAction;actionDone?:boolean;report?:boolean}
type Props={engine:AiResearchEngine|null;jobs:AiResearchJob[];onAsk:(question:string,history:{role:'user'|'assistant';content:string}[])=>Promise<FelixResponse>;onAction:(action:FelixAction)=>Promise<string>}

export default function AIResearchChat({engine,jobs,onAsk,onAction}:Props){
  const [question,setQuestion]=useState('')
  const [sending,setSending]=useState(false)
  const [messages,setMessages]=useState<Message[]>([{role:'assistant',text:'Hello, I am Felix, your PSC AI Research Assistant. Ask about App2, notices, assignments, reports or approved documents. I can also prepare controlled actions for your confirmation.'}])
  const send=async()=>{const text=question.trim();if(!text||sending)return;const history=messages.map(item=>({role:item.role,content:item.text}));setQuestion('');setMessages(current=>[...current,{role:'user',text}]);setSending(true);try{const response=await onAsk(text,history);setMessages(current=>[...current,{role:'assistant',text:response.answer,references:response.references,action:response.action,report:response.report}])}catch(error){setMessages(current=>[...current,{role:'assistant',text:error instanceof Error?error.message:'I could not answer that just now. Please try again.'}])}finally{setSending(false)}}
  const confirmAction=async(index:number,action:FelixAction)=>{setSending(true);try{const result=await onAction(action);setMessages(current=>current.map((item,itemIndex)=>itemIndex===index?{...item,actionDone:true,text:`${item.text}\n\n${result}`}:item))}catch(error){setMessages(current=>current.map((item,itemIndex)=>itemIndex===index?{...item,text:`${item.text}\n\n${error instanceof Error?error.message:'The action could not be completed.'}`}:item))}finally{setSending(false)}}
  const downloadReport=(content:string)=>{const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`app2-report-${new Date().toISOString().slice(0,10)}.txt`;link.click();URL.revokeObjectURL(url)}
  return <div className="ai-chat-layout"><section className="ai-chat"><header><div><strong>Chat with Felix</strong><small>App2-aware assistant · Confirm actions before execution</small></div><b className={engine?.ollamaConnected?'online':'offline'}>{engine?.ollamaConnected?'Local AI online':'Local AI offline'}</b></header><div className="ai-chat-messages">{messages.map((message,index)=><article className={message.role} key={index}><span>{message.role==='assistant'?'Felix':'You'}</span><div className="ai-message-content"><p>{message.text}</p>{message.references?.length?<small className="felix-references">Sources: {message.references.join(' · ')}</small>:null}{message.report?<button className="felix-download-report" onClick={()=>downloadReport(message.text)}>Download report</button>:null}{message.action&&!message.actionDone?<button className="felix-confirm-action" disabled={sending} onClick={()=>confirmAction(index,message.action!)}>{message.action.label}</button>:null}{message.actionDone?<small className="felix-action-done">✓ Action confirmed</small>:null}</div></article>)}{sending&&<article className="assistant"><span>Felix</span><div className="ai-message-content"><p>Working…</p></div></article>}</div><div className="ai-chat-input"><textarea value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send()}}} placeholder="Ask Felix about App2 or request a report…"/><button onClick={send} disabled={!question.trim()||sending}>Send</button></div><small className="ai-chat-scope">Felix uses your App2 permissions. Reports use live visible records; record changes require confirmation and remain subject to role checks and audit logging.</small></section><aside className="ai-chat-history"><h3>Research history</h3>{jobs.slice(0,8).map(job=><article key={job.id}><span>{job.status}</span><strong>{job.title}</strong><small>{job.question}</small></article>)}{!jobs.length&&<p>No research conversations yet.</p>}</aside></div>
}
