import { useEffect, useState } from 'react'
import { api, type FelixAdminOverview } from './api'

const when=(value:string|null|undefined)=>value?new Date(value).toLocaleString('en-KE'):'Not available'
const pct=(supported:number,total:number)=>total?Math.round((supported/total)*100):0

export default function FelixAdmin({token}:{token:string}){
  const [data,setData]=useState<FelixAdminOverview|null>(null)
  const [error,setError]=useState('')
  const [loading,setLoading]=useState(true)
  const load=async()=>{setLoading(true);setError('');try{setData(await api.felixAdminOverview(token))}catch(error){setError(error instanceof Error?error.message:'Felix administration data could not be loaded.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[token])
  if(loading&&!data)return <section className="felix-admin-loading"><strong>Loading Felix administration…</strong><span>Checking local AI, indexes, reviews and audit records.</span></section>
  if(!data)return <section className="felix-admin-loading error"><strong>Felix administration unavailable</strong><span>{error}</span><button onClick={load}>Try again</button></section>
  const citationRate=pct(data.quality.citations.supported,data.quality.citations.total)
  return <section className="felix-admin-dashboard">
    <header className="felix-admin-head"><div><p>FELIX ADMINISTRATION</p><h2>AI assurance and operations</h2><span>Live health, evidence quality, repository controls, automated reviews, approvals and immutable audit activity.</span></div><button onClick={load} disabled={loading}>{loading?'Refreshing…':'Refresh data'}</button></header>
    {error&&<div className="felix-admin-alert">{error}</div>}
    <div className="felix-admin-kpis">
      <article className={data.engine.ollamaConnected?'healthy':'critical'}><span>Local model</span><strong>{data.engine.ollamaConnected?'Online':'Offline'}</strong><small>{data.engine.model}</small></article>
      <article><span>Indexed documents</span><strong>{data.documents.indexed_documents}</strong><small>{data.documents.indexed_chunks} searchable chunks</small></article>
      <article><span>Indexed repositories</span><strong>{data.repositories.length}</strong><small>{data.repositories.reduce((sum,item)=>sum+item.indexed_files,0)} source files</small></article>
      <article className={citationRate>=80?'healthy':citationRate>=50?'warning':'critical'}><span>Citation support</span><strong>{citationRate}%</strong><small>{data.quality.citations.supported} of {data.quality.citations.total} validated</small></article>
      <article className={data.failedIndexingJobs.length?'critical':'healthy'}><span>Failed indexes</span><strong>{data.failedIndexingJobs.length}</strong><small>{data.failedIndexingJobs.length?'Needs attention':'No recent failures'}</small></article>
      <article className={data.pendingApprovals.length?'warning':'healthy'}><span>Pending approvals</span><strong>{data.pendingApprovals.length}</strong><small>All remain Not Applied</small></article>
    </div>
    <div className="felix-admin-grid">
      <article className="felix-admin-panel repository-panel"><header><div><p>REPOSITORY</p><h3>Current App2 source</h3></div><b>{data.liveRepository.branch}</b></header><dl><div><dt>Repository</dt><dd>{data.liveRepository.repository}</dd></div><div><dt>Commit</dt><dd><code>{data.liveRepository.commit}</code></dd></div><div><dt>Last document index</dt><dd>{when(data.documents.last_document_indexed_at)}</dd></div></dl>{data.repositories.map(item=><div className="repository-row" key={item.id}><span><strong>{item.name}</strong><small>{item.indexed_files} files · indexed {when(item.last_indexed_at)}</small></span><code>{item.branch||'unknown'} · {(item.commit_hash||'unknown').slice(0,12)}</code></div>)}</article>
      <article className="felix-admin-panel"><header><div><p>QUALITY</p><h3>Research and citations</h3></div><b>{data.quality.research.total} jobs</b></header><div className="quality-bars"><label><span>Citation validation</span><b>{citationRate}%</b><i><em style={{width:`${citationRate}%`}}/></i></label><label><span>Average evidence score</span><b>{Math.round(Number(data.quality.citations.average_score)*100)}%</b><i><em style={{width:`${Math.round(Number(data.quality.citations.average_score)*100)}%`}}/></i></label></div><div className="mini-stats"><span><b>{data.quality.research.approved}</b> Approved</span><span><b>{data.quality.research.draft_ready}</b> Draft ready</span><span><b>{data.quality.research.failed}</b> Failed</span></div></article>
      <article className="felix-admin-panel wide"><header><div><p>ASSURANCE</p><h3>Code-review and security findings</h3></div><b>{data.findings.length} recent</b></header><div className="felix-admin-table"><div><span>Severity</span><span>Finding</span><span>Evidence</span><span>Status</span></div>{data.findings.slice(0,12).map(item=><div key={`${item.finding_id}-${item.created_at}`}><b className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</b><span><strong>{item.finding_id} · {item.category}</strong><small>{item.description}</small></span><code>{item.file_path}:{item.start_line}</code><em>{item.review_status}</em></div>)}{!data.findings.length&&<p>No code-review findings recorded.</p>}</div></article>
      <article className="felix-admin-panel"><header><div><p>AUTOMATION</p><h3>Review schedules</h3></div><b>{data.reviewSchedules.filter(item=>item.enabled).length} enabled</b></header><div className="schedule-list">{data.reviewSchedules.map(item=><div key={item.id}><span className={item.enabled?'on':'off'}>{item.enabled?'On':'Off'}</span><span><strong>{item.name}</strong><small>{item.trigger_type} · next {when(item.next_run_at)}</small></span></div>)}</div></article>
      <article className="felix-admin-panel"><header><div><p>TESTS & DEPENDENCIES</p><h3>Latest automated checks</h3></div><b>{data.dependencyAlerts.length} alerts</b></header><div className="check-list">{data.testResults.slice(0,8).map((item,index)=><div key={`${item.started_at}-${index}`}><span className={item.status==='Passed'?'passed':'failed'}>{item.status}</span><span><strong>{item.command_label}</strong><small>{item.profile} · {item.duration_ms||0} ms</small></span></div>)}{!data.testResults.length&&<p>No scheduled test results yet.</p>}</div>{data.dependencyAlerts.slice(0,3).map((item,index)=><div className="dependency-alert" key={`${item.started_at}-${index}`}><strong>{item.command_label}</strong><span>{item.status} · {item.profile}</span></div>)}</article>
      <article className="felix-admin-panel"><header><div><p>APPROVALS</p><h3>Manual change control</h3></div><b>{data.pendingApprovals.length} pending</b></header><div className="approval-list">{data.pendingApprovals.map(item=><div key={item.id}><span><strong>{item.file_path}</strong><small>{item.risk_level} risk · {item.proposed_by_name}</small></span><b>{item.application_status}</b></div>)}{!data.pendingApprovals.length&&<p>No patches awaiting approval.</p>}</div></article>
      <article className="felix-admin-panel wide"><header><div><p>IMMUTABLE AUDIT</p><h3>Recent Felix events</h3></div><b>{data.auditEvents.length} shown</b></header><div className="audit-event-list">{data.auditEvents.map(item=><div key={item.id}><time>{when(item.occurred_at)}</time><span><strong>{item.event_type} · {item.operating_mode}</strong><small>{item.user_name||'Felix Scheduler'} · {item.query||'No query'}</small></span><b className={item.final_outcome.toLowerCase()}>{item.final_outcome}</b></div>)}</div></article>
    </div>
  </section>
}
