import {useEffect,useRef,useState} from 'react'
import {GlobalWorkerOptions,getDocument,type PDFDocumentProxy} from 'pdfjs-dist'
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import {api,type DocumentItem} from './api'
import FelixCharacter from './components/felix/FelixCharacter'
import FelixStatus from './components/felix/FelixStatus'
import {useFelixVisualState} from './components/felix/animations/FelixAnimationController'
import './document-reader.css'

GlobalWorkerOptions.workerSrc=pdfWorker
const API_URL=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000/api'
type ReaderPayload={format:'docx'|'text'|'markdown';html:string;text:string;warnings?:string[];metadata:{versionId:string;version:number;isCurrent:boolean;canDownload:boolean}}
type FelixAssessment={overall_assessment:string;classification:{document_type:string;confidence:string};framework:{name:string;source:string};strengths:Array<{title:string;explanation:string}>;findings:Array<{kind:string;title:string;explanation:string}>;questions:string[];recommendations:Array<{priority:string;title:string;recommended_action:string}>;citations:Array<{title:string;page?:number;section?:string;chunk_id:string}>;limitations:string}

export default function DocumentReader({token,document,versionId,onClose}:{token:string;document:DocumentItem;versionId?:string;onClose:()=>void}){
  const {state:felixState,beginOperation:beginFelix,completeOperation:completeFelix,failOperation:failFelix}=useFelixVisualState()
  const [payload,setPayload]=useState<ReaderPayload|null>(null),[pdf,setPdf]=useState<PDFDocumentProxy|null>(null),[page,setPage]=useState(1),[zoom,setZoom]=useState(1),[fit,setFit]=useState(true)
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[matches,setMatches]=useState<number[]>([]),[matchIndex,setMatchIndex]=useState(0),[infoOpen,setInfoOpen]=useState(true),[felixOpen,setFelixOpen]=useState(false),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[asking,setAsking]=useState(false),[assessment,setAssessment]=useState<FelixAssessment|null>(null),[assessing,setAssessing]=useState(false),[assessmentError,setAssessmentError]=useState('')
  const canvasRef=useRef<HTMLCanvasElement>(null),readerRef=useRef<HTMLElement>(null)
  const readerUrl=`${API_URL}/documents/${document.id}${versionId?`/versions/${versionId}`:''}/reader`
  const classification=document.classification||'INTERNAL',historical=versionId?payload?!payload.metadata.isCurrent:true:false
  useEffect(()=>{let cancelled=false;setLoading(true);setError('');setPayload(null);setPdf(null);fetch(readerUrl,{headers:{Authorization:`Bearer ${token}`}}).then(async response=>{if(!response.ok)throw new Error((await response.json().catch(()=>null))?.error||'Document could not be opened.');if((response.headers.get('content-type')||'').includes('application/pdf')){const bytes=await response.arrayBuffer();const loaded=await getDocument({data:bytes}).promise;if(!cancelled){setPdf(loaded);const remembered=Number(localStorage.getItem(`app2-reader-${document.id}-${versionId||'current'}`)||1);setPage(Math.min(Math.max(1,remembered),loaded.numPages))}}else{const data=await response.json();if(!cancelled)setPayload(data)}}).catch(value=>!cancelled&&setError(value instanceof Error?value.message:'Document could not be opened.')).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}},[readerUrl,token,document.id,versionId])
  useEffect(()=>{if(!pdf||!canvasRef.current)return;let cancelled=false;pdf.getPage(page).then(async pdfPage=>{if(cancelled||!canvasRef.current)return;const base=pdfPage.getViewport({scale:1});const available=Math.max(320,(readerRef.current?.clientWidth||900)-48);const scale=fit?available/base.width:zoom;const viewport=pdfPage.getViewport({scale});const canvas=canvasRef.current,context=canvas.getContext('2d');if(!context)return;const ratio=window.devicePixelRatio||1;canvas.width=viewport.width*ratio;canvas.height=viewport.height*ratio;canvas.style.width=`${viewport.width}px`;canvas.style.height=`${viewport.height}px`;await pdfPage.render({canvas,canvasContext:context,viewport,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]}).promise;localStorage.setItem(`app2-reader-${document.id}-${versionId||'current'}`,String(page))}).catch(()=>setError('This PDF page could not be rendered.'));return()=>{cancelled=true}},[pdf,page,zoom,fit,document.id,versionId])
  useEffect(()=>{let cancelled=false;if(!search.trim()){setMatches([]);setMatchIndex(0);return}if(pdf){Promise.all(Array.from({length:pdf.numPages},(_,index)=>pdf.getPage(index+1).then(item=>item.getTextContent()).then(content=>({page:index+1,text:content.items.map(value=>'str'in value?value.str:'').join(' ')})))).then(pages=>{if(cancelled)return;const needle=search.toLowerCase();const found=pages.flatMap(item=>Array.from({length:item.text.toLowerCase().split(needle).length-1},()=>item.page));setMatches(found);setMatchIndex(0);if(found[0])setPage(found[0])})}else if(payload){const count=payload.text.toLowerCase().split(search.toLowerCase()).length-1;setMatches(Array.from({length:count},()=>1));setMatchIndex(0)}return()=>{cancelled=true}},[search,pdf,payload])
  const currentVersion=payload?.metadata.version||document.latest_version||document.current_version||1
  const nextMatch=(direction:number)=>{if(!matches.length)return;const next=(matchIndex+direction+matches.length)%matches.length;setMatchIndex(next);if(pdf)setPage(matches[next])}
  const askFelix=async()=>{if(!question.trim())return;setAsking(true);setAnswer('');beginFelix('document_summary');try{const result=await api.askDocumentFelix(token,document.id,question.trim());setAnswer(result.answer);completeFelix(/insufficient|cannot assess/i.test(result.answer)?'insufficient_evidence':'presenting')}catch(value){failFelix();setAnswer(value instanceof Error?value.message:'Felix could not answer.')}finally{setAsking(false)}}
  const auditFelix=async()=>{setFelixOpen(true);setInfoOpen(false);setAssessing(true);setAssessmentError('');setAssessment(null);beginFelix('document_audit');try{const value=await api.assessDocumentFelix(token,document.id) as FelixAssessment;setAssessment(value);completeFelix(value.overall_assessment==='READY'||value.overall_assessment==='READY WITH MINOR ISSUES'?'success':value.overall_assessment==='UNABLE TO ASSESS'?'insufficient_evidence':'found_issue')}catch(value){failFelix();setAssessmentError(value instanceof Error?value.message:'Felix could not assess this document.')}finally{setAssessing(false)}}
  const contextualQuestions=/policy/i.test(`${document.category} ${document.document_type}`)?['What are the mandatory requirements?','Who is responsible?','What implementation gaps exist?']:/minute/i.test(`${document.category} ${document.document_type}`)?['What decisions were made?','What actions remain outstanding?','Who owns them?']:['Summarize this document','What are the strongest findings?','What are its limitations?','Are the conclusions justified?']
  return <div className="document-reader-shell" role="dialog" aria-modal="true" aria-label={`Read ${document.title}`}>
    <header><button onClick={onClose}>← Repository</button><div><small>{document.category} · Version {currentVersion} · {document.status}</small><h1>{document.title}</h1></div><div className="reader-head-actions"><button onClick={()=>setInfoOpen(value=>!value)}>Information</button><button onClick={()=>{setFelixOpen(true);setInfoOpen(false)}}>Ask Felix</button><button onClick={auditFelix}>Audit</button><button onClick={()=>{setFelixOpen(true);setInfoOpen(false);setQuestion('Find related approved App2 research and explain the relationship.')}}>Related research</button><button aria-label="Close reader" onClick={onClose}>×</button></div></header>
    {historical&&<div className="reader-history-banner">You are viewing a historical document version.</div>}
    {['CONFIDENTIAL','RESTRICTED'].includes(classification)&&<div className={`reader-classification ${classification.toLowerCase()}`}>{classification} — Authorized App2 Users Only</div>}
    <nav className="reader-toolbar"><label><span>Search document</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search document..."/></label><span>{matches.length?`${matchIndex+1} of ${matches.length}`:'0 matches'}</span><button disabled={!matches.length} onClick={()=>nextMatch(-1)}>Previous match</button><button disabled={!matches.length} onClick={()=>nextMatch(1)}>Next match</button>{pdf&&<><i/><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous page</button><strong>Page {page} of {pdf.numPages}</strong><button disabled={page>=pdf.numPages} onClick={()=>setPage(value=>value+1)}>Next page</button><i/><button onClick={()=>{setFit(false);setZoom(value=>Math.max(.5,value-.15))}}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>{setFit(false);setZoom(value=>Math.min(2.5,value+.15))}}>+</button><button className={fit?'active':''} onClick={()=>setFit(true)}>Fit width</button></>}<button onClick={()=>readerRef.current?.requestFullscreen?.()}>Full screen</button></nav>
    <main><section className={`reader-stage ${payload?.format||'pdf'}`} ref={readerRef}>{loading&&<div className="reader-state">Opening secure document…</div>}{error&&<div className="reader-state error"><strong>Document unavailable</strong><span>{error}</span><button onClick={onClose}>Back to Repository</button></div>}{pdf&&<canvas ref={canvasRef}/>} {payload&&<article dangerouslySetInnerHTML={{__html:payload.html}}/>}</section>
    {felixOpen&&<div className="reader-felix-presence"><FelixCharacter state={felixState} size="sm"/><FelixStatus state={felixState}/></div>}
    {infoOpen&&<aside className="reader-info"><h2>Document information</h2><dl><dt>Classification</dt><dd><b>{classification}</b></dd><dt>Version</dt><dd>{currentVersion}{historical?' · Historical':' · Current'}</dd><dt>Status</dt><dd>{document.status}</dd><dt>Category</dt><dd>{document.category}</dd><dt>Directorate</dt><dd>{document.directorate||'Not specified'}</dd><dt>Author</dt><dd>{document.author||'Not specified'}</dd><dt>Uploaded by</dt><dd>{document.created_by_name}</dd><dt>Tags</dt><dd>{document.tags?.join(', ')||'None'}</dd></dl><p>{document.description}</p>{payload?.metadata.canDownload&&<button onClick={()=>api.downloadKnowledgeVersion(token,payload.metadata.versionId,document.original_name)}>Download this version</button>}</aside>}
    {felixOpen&&<aside className="reader-felix"><div className="reader-felix-title"><div><small>Approved evidence only</small><h2>Felix</h2></div><button aria-label="Close Felix" onClick={()=>setFelixOpen(false)}>×</button></div><div className="reader-felix-prompts">{contextualQuestions.map(item=><button key={item} onClick={()=>setQuestion(item)}>{item}</button>)}</div><textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Ask about this document…"/><button disabled={asking||!question.trim()} onClick={askFelix}>{asking?'Reading…':'Ask Felix'}</button>{answer&&<div className="reader-felix-answer">{answer}</div>}{assessing&&<div className="reader-felix-state">Running a structured evidence audit…</div>}{assessmentError&&<div className="reader-felix-state error">{assessmentError}</div>}{assessment&&<section className="reader-assessment"><header><div><small>Felix Assessment</small><h3>{assessment.overall_assessment.replaceAll('_',' ')}</h3></div><span>{assessment.classification.confidence}</span></header><p><b>{assessment.classification.document_type.replaceAll('_',' ')}</b> · {assessment.framework.name}</p>{assessment.strengths.length>0&&<div><h4>Strong</h4>{assessment.strengths.map(item=><article key={item.title}><b>{item.title}</b><p>{item.explanation}</p></article>)}</div>}<div><h4>Needs attention</h4>{assessment.findings.filter(item=>item.kind==='GAP').map(item=><article key={item.title}><b>{item.title}</b><p>{item.explanation}</p></article>)}</div><div><h4>Questions Felix would ask</h4><ul>{assessment.questions.map(item=><li key={item}>{item}</li>)}</ul></div><div><h4>Suggested actions</h4>{assessment.recommendations.map(item=><article key={item.title}><small>{item.priority}</small><b>{item.title}</b><p>{item.recommended_action}</p></article>)}</div><details><summary>Sources and limitations</summary><p>{assessment.framework.source}</p><ul>{assessment.citations.slice(0,8).map(item=><li key={item.chunk_id}>{item.title}{item.page?` · page ${item.page}`:''}{item.section?` · ${item.section}`:''}</li>)}</ul><p>{assessment.limitations}</p></details></section>}</aside>}</main>
  </div>
}
